package tiger.common.dal.persistence.icbc;

import java.util.Date;

public class RegisterInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Agt_Num
     *
     * @mbggenerated
     */
    private String agtNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Agt_Modif_Num
     *
     * @mbggenerated
     */
    private String agtModifNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Prod_Id
     *
     * @mbggenerated
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Biz_Type_Num
     *
     * @mbggenerated
     */
    private String bizTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Zone_Num
     *
     * @mbggenerated
     */
    private Integer zoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Int_Org_Num
     *
     * @mbggenerated
     */
    private String intOrgNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Party_Id
     *
     * @mbggenerated
     */
    private String partyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Agt_Status_Cd
     *
     * @mbggenerated
     */
    private String agtStatusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Rgst_Mode_Cd
     *
     * @mbggenerated
     */
    private String rgstModeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Open_Acct_Dt
     *
     * @mbggenerated
     */
    private Date openAcctDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Open_Acct_Tm
     *
     * @mbggenerated
     */
    private String openAcctTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Close_Acct_Dt
     *
     * @mbggenerated
     */
    private Date closeAcctDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Mobile_Msg_Att_Open_Ind
     *
     * @mbggenerated
     */
    private String mobileMsgAttOpenInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Bind_Mobile_Num
     *
     * @mbggenerated
     */
    private String bindMobileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Ext_Tran_Ind
     *
     * @mbggenerated
     */
    private String extTranInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.WebBank_Cust_Type_Cd
     *
     * @mbggenerated
     */
    private String webbankCustTypeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.WebBank_Cust_Level
     *
     * @mbggenerated
     */
    private String webbankCustLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Att_Med_Type
     *
     * @mbggenerated
     */
    private String attMedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.U_Shd_Att_Med_Seq_Num
     *
     * @mbggenerated
     */
    private String uShdAttMedSeqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Move_Pwd_Card_Att_Med_Num
     *
     * @mbggenerated
     */
    private String movePwdCardAttMedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Down_Card_Num
     *
     * @mbggenerated
     */
    private String downCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Down_Acct_Num
     *
     * @mbggenerated
     */
    private String downAcctNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Down_Card_Belong_Org_Num
     *
     * @mbggenerated
     */
    private String downCardBelongOrgNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Down_Acct_Belong_Org_Num
     *
     * @mbggenerated
     */
    private String downAcctBelongOrgNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Last_Logon_Dt
     *
     * @mbggenerated
     */
    private Date lastLogonDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Last_Logon_Tm
     *
     * @mbggenerated
     */
    private String lastLogonTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.Last_Tx_Dt
     *
     * @mbggenerated
     */
    private Date lastTxDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.id
     *
     * @return the value of registerinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.id
     *
     * @param id the value for registerinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Agt_Num
     *
     * @return the value of registerinfo.Agt_Num
     *
     * @mbggenerated
     */
    public String getAgtNum() {
        return agtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Agt_Num
     *
     * @param agtNum the value for registerinfo.Agt_Num
     *
     * @mbggenerated
     */
    public void setAgtNum(String agtNum) {
        this.agtNum = agtNum == null ? null : agtNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Agt_Modif_Num
     *
     * @return the value of registerinfo.Agt_Modif_Num
     *
     * @mbggenerated
     */
    public String getAgtModifNum() {
        return agtModifNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Agt_Modif_Num
     *
     * @param agtModifNum the value for registerinfo.Agt_Modif_Num
     *
     * @mbggenerated
     */
    public void setAgtModifNum(String agtModifNum) {
        this.agtModifNum = agtModifNum == null ? null : agtModifNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Prod_Id
     *
     * @return the value of registerinfo.Prod_Id
     *
     * @mbggenerated
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Prod_Id
     *
     * @param prodId the value for registerinfo.Prod_Id
     *
     * @mbggenerated
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Biz_Type_Num
     *
     * @return the value of registerinfo.Biz_Type_Num
     *
     * @mbggenerated
     */
    public String getBizTypeNum() {
        return bizTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Biz_Type_Num
     *
     * @param bizTypeNum the value for registerinfo.Biz_Type_Num
     *
     * @mbggenerated
     */
    public void setBizTypeNum(String bizTypeNum) {
        this.bizTypeNum = bizTypeNum == null ? null : bizTypeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Zone_Num
     *
     * @return the value of registerinfo.Zone_Num
     *
     * @mbggenerated
     */
    public Integer getZoneNum() {
        return zoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Zone_Num
     *
     * @param zoneNum the value for registerinfo.Zone_Num
     *
     * @mbggenerated
     */
    public void setZoneNum(Integer zoneNum) {
        this.zoneNum = zoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Int_Org_Num
     *
     * @return the value of registerinfo.Int_Org_Num
     *
     * @mbggenerated
     */
    public String getIntOrgNum() {
        return intOrgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Int_Org_Num
     *
     * @param intOrgNum the value for registerinfo.Int_Org_Num
     *
     * @mbggenerated
     */
    public void setIntOrgNum(String intOrgNum) {
        this.intOrgNum = intOrgNum == null ? null : intOrgNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Party_Id
     *
     * @return the value of registerinfo.Party_Id
     *
     * @mbggenerated
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Party_Id
     *
     * @param partyId the value for registerinfo.Party_Id
     *
     * @mbggenerated
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId == null ? null : partyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Agt_Status_Cd
     *
     * @return the value of registerinfo.Agt_Status_Cd
     *
     * @mbggenerated
     */
    public String getAgtStatusCd() {
        return agtStatusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Agt_Status_Cd
     *
     * @param agtStatusCd the value for registerinfo.Agt_Status_Cd
     *
     * @mbggenerated
     */
    public void setAgtStatusCd(String agtStatusCd) {
        this.agtStatusCd = agtStatusCd == null ? null : agtStatusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Rgst_Mode_Cd
     *
     * @return the value of registerinfo.Rgst_Mode_Cd
     *
     * @mbggenerated
     */
    public String getRgstModeCd() {
        return rgstModeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Rgst_Mode_Cd
     *
     * @param rgstModeCd the value for registerinfo.Rgst_Mode_Cd
     *
     * @mbggenerated
     */
    public void setRgstModeCd(String rgstModeCd) {
        this.rgstModeCd = rgstModeCd == null ? null : rgstModeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Open_Acct_Dt
     *
     * @return the value of registerinfo.Open_Acct_Dt
     *
     * @mbggenerated
     */
    public Date getOpenAcctDt() {
        return openAcctDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Open_Acct_Dt
     *
     * @param openAcctDt the value for registerinfo.Open_Acct_Dt
     *
     * @mbggenerated
     */
    public void setOpenAcctDt(Date openAcctDt) {
        this.openAcctDt = openAcctDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Open_Acct_Tm
     *
     * @return the value of registerinfo.Open_Acct_Tm
     *
     * @mbggenerated
     */
    public String getOpenAcctTm() {
        return openAcctTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Open_Acct_Tm
     *
     * @param openAcctTm the value for registerinfo.Open_Acct_Tm
     *
     * @mbggenerated
     */
    public void setOpenAcctTm(String openAcctTm) {
        this.openAcctTm = openAcctTm == null ? null : openAcctTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Close_Acct_Dt
     *
     * @return the value of registerinfo.Close_Acct_Dt
     *
     * @mbggenerated
     */
    public Date getCloseAcctDt() {
        return closeAcctDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Close_Acct_Dt
     *
     * @param closeAcctDt the value for registerinfo.Close_Acct_Dt
     *
     * @mbggenerated
     */
    public void setCloseAcctDt(Date closeAcctDt) {
        this.closeAcctDt = closeAcctDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Mobile_Msg_Att_Open_Ind
     *
     * @return the value of registerinfo.Mobile_Msg_Att_Open_Ind
     *
     * @mbggenerated
     */
    public String getMobileMsgAttOpenInd() {
        return mobileMsgAttOpenInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Mobile_Msg_Att_Open_Ind
     *
     * @param mobileMsgAttOpenInd the value for registerinfo.Mobile_Msg_Att_Open_Ind
     *
     * @mbggenerated
     */
    public void setMobileMsgAttOpenInd(String mobileMsgAttOpenInd) {
        this.mobileMsgAttOpenInd = mobileMsgAttOpenInd == null ? null : mobileMsgAttOpenInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Bind_Mobile_Num
     *
     * @return the value of registerinfo.Bind_Mobile_Num
     *
     * @mbggenerated
     */
    public String getBindMobileNum() {
        return bindMobileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Bind_Mobile_Num
     *
     * @param bindMobileNum the value for registerinfo.Bind_Mobile_Num
     *
     * @mbggenerated
     */
    public void setBindMobileNum(String bindMobileNum) {
        this.bindMobileNum = bindMobileNum == null ? null : bindMobileNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Ext_Tran_Ind
     *
     * @return the value of registerinfo.Ext_Tran_Ind
     *
     * @mbggenerated
     */
    public String getExtTranInd() {
        return extTranInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Ext_Tran_Ind
     *
     * @param extTranInd the value for registerinfo.Ext_Tran_Ind
     *
     * @mbggenerated
     */
    public void setExtTranInd(String extTranInd) {
        this.extTranInd = extTranInd == null ? null : extTranInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.WebBank_Cust_Type_Cd
     *
     * @return the value of registerinfo.WebBank_Cust_Type_Cd
     *
     * @mbggenerated
     */
    public String getWebbankCustTypeCd() {
        return webbankCustTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.WebBank_Cust_Type_Cd
     *
     * @param webbankCustTypeCd the value for registerinfo.WebBank_Cust_Type_Cd
     *
     * @mbggenerated
     */
    public void setWebbankCustTypeCd(String webbankCustTypeCd) {
        this.webbankCustTypeCd = webbankCustTypeCd == null ? null : webbankCustTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.WebBank_Cust_Level
     *
     * @return the value of registerinfo.WebBank_Cust_Level
     *
     * @mbggenerated
     */
    public String getWebbankCustLevel() {
        return webbankCustLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.WebBank_Cust_Level
     *
     * @param webbankCustLevel the value for registerinfo.WebBank_Cust_Level
     *
     * @mbggenerated
     */
    public void setWebbankCustLevel(String webbankCustLevel) {
        this.webbankCustLevel = webbankCustLevel == null ? null : webbankCustLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Att_Med_Type
     *
     * @return the value of registerinfo.Att_Med_Type
     *
     * @mbggenerated
     */
    public String getAttMedType() {
        return attMedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Att_Med_Type
     *
     * @param attMedType the value for registerinfo.Att_Med_Type
     *
     * @mbggenerated
     */
    public void setAttMedType(String attMedType) {
        this.attMedType = attMedType == null ? null : attMedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.U_Shd_Att_Med_Seq_Num
     *
     * @return the value of registerinfo.U_Shd_Att_Med_Seq_Num
     *
     * @mbggenerated
     */
    public String getuShdAttMedSeqNum() {
        return uShdAttMedSeqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.U_Shd_Att_Med_Seq_Num
     *
     * @param uShdAttMedSeqNum the value for registerinfo.U_Shd_Att_Med_Seq_Num
     *
     * @mbggenerated
     */
    public void setuShdAttMedSeqNum(String uShdAttMedSeqNum) {
        this.uShdAttMedSeqNum = uShdAttMedSeqNum == null ? null : uShdAttMedSeqNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Move_Pwd_Card_Att_Med_Num
     *
     * @return the value of registerinfo.Move_Pwd_Card_Att_Med_Num
     *
     * @mbggenerated
     */
    public String getMovePwdCardAttMedNum() {
        return movePwdCardAttMedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Move_Pwd_Card_Att_Med_Num
     *
     * @param movePwdCardAttMedNum the value for registerinfo.Move_Pwd_Card_Att_Med_Num
     *
     * @mbggenerated
     */
    public void setMovePwdCardAttMedNum(String movePwdCardAttMedNum) {
        this.movePwdCardAttMedNum = movePwdCardAttMedNum == null ? null : movePwdCardAttMedNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Down_Card_Num
     *
     * @return the value of registerinfo.Down_Card_Num
     *
     * @mbggenerated
     */
    public String getDownCardNum() {
        return downCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Down_Card_Num
     *
     * @param downCardNum the value for registerinfo.Down_Card_Num
     *
     * @mbggenerated
     */
    public void setDownCardNum(String downCardNum) {
        this.downCardNum = downCardNum == null ? null : downCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Down_Acct_Num
     *
     * @return the value of registerinfo.Down_Acct_Num
     *
     * @mbggenerated
     */
    public String getDownAcctNum() {
        return downAcctNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Down_Acct_Num
     *
     * @param downAcctNum the value for registerinfo.Down_Acct_Num
     *
     * @mbggenerated
     */
    public void setDownAcctNum(String downAcctNum) {
        this.downAcctNum = downAcctNum == null ? null : downAcctNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Down_Card_Belong_Org_Num
     *
     * @return the value of registerinfo.Down_Card_Belong_Org_Num
     *
     * @mbggenerated
     */
    public String getDownCardBelongOrgNum() {
        return downCardBelongOrgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Down_Card_Belong_Org_Num
     *
     * @param downCardBelongOrgNum the value for registerinfo.Down_Card_Belong_Org_Num
     *
     * @mbggenerated
     */
    public void setDownCardBelongOrgNum(String downCardBelongOrgNum) {
        this.downCardBelongOrgNum = downCardBelongOrgNum == null ? null : downCardBelongOrgNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Down_Acct_Belong_Org_Num
     *
     * @return the value of registerinfo.Down_Acct_Belong_Org_Num
     *
     * @mbggenerated
     */
    public String getDownAcctBelongOrgNum() {
        return downAcctBelongOrgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Down_Acct_Belong_Org_Num
     *
     * @param downAcctBelongOrgNum the value for registerinfo.Down_Acct_Belong_Org_Num
     *
     * @mbggenerated
     */
    public void setDownAcctBelongOrgNum(String downAcctBelongOrgNum) {
        this.downAcctBelongOrgNum = downAcctBelongOrgNum == null ? null : downAcctBelongOrgNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Last_Logon_Dt
     *
     * @return the value of registerinfo.Last_Logon_Dt
     *
     * @mbggenerated
     */
    public Date getLastLogonDt() {
        return lastLogonDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Last_Logon_Dt
     *
     * @param lastLogonDt the value for registerinfo.Last_Logon_Dt
     *
     * @mbggenerated
     */
    public void setLastLogonDt(Date lastLogonDt) {
        this.lastLogonDt = lastLogonDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Last_Logon_Tm
     *
     * @return the value of registerinfo.Last_Logon_Tm
     *
     * @mbggenerated
     */
    public String getLastLogonTm() {
        return lastLogonTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Last_Logon_Tm
     *
     * @param lastLogonTm the value for registerinfo.Last_Logon_Tm
     *
     * @mbggenerated
     */
    public void setLastLogonTm(String lastLogonTm) {
        this.lastLogonTm = lastLogonTm == null ? null : lastLogonTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.Last_Tx_Dt
     *
     * @return the value of registerinfo.Last_Tx_Dt
     *
     * @mbggenerated
     */
    public Date getLastTxDt() {
        return lastTxDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registerinfo.Last_Tx_Dt
     *
     * @param lastTxDt the value for registerinfo.Last_Tx_Dt
     *
     * @mbggenerated
     */
    public void setLastTxDt(Date lastTxDt) {
        this.lastTxDt = lastTxDt;
    }
}