package tiger.common.dal.persistence.socialnet;

import java.util.ArrayList;
import java.util.List;

public class SocialnetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public SocialnetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealidIsNull() {
            addCriterion("dealid is null");
            return (Criteria) this;
        }

        public Criteria andDealidIsNotNull() {
            addCriterion("dealid is not null");
            return (Criteria) this;
        }

        public Criteria andDealidEqualTo(Long value) {
            addCriterion("dealid =", value, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidNotEqualTo(Long value) {
            addCriterion("dealid <>", value, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidGreaterThan(Long value) {
            addCriterion("dealid >", value, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidGreaterThanOrEqualTo(Long value) {
            addCriterion("dealid >=", value, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidLessThan(Long value) {
            addCriterion("dealid <", value, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidLessThanOrEqualTo(Long value) {
            addCriterion("dealid <=", value, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidIn(List<Long> values) {
            addCriterion("dealid in", values, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidNotIn(List<Long> values) {
            addCriterion("dealid not in", values, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidBetween(Long value1, Long value2) {
            addCriterion("dealid between", value1, value2, "dealid");
            return (Criteria) this;
        }

        public Criteria andDealidNotBetween(Long value1, Long value2) {
            addCriterion("dealid not between", value1, value2, "dealid");
            return (Criteria) this;
        }

        public Criteria andU1IsNull() {
            addCriterion("u1 is null");
            return (Criteria) this;
        }

        public Criteria andU1IsNotNull() {
            addCriterion("u1 is not null");
            return (Criteria) this;
        }

        public Criteria andU1EqualTo(String value) {
            addCriterion("u1 =", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1NotEqualTo(String value) {
            addCriterion("u1 <>", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1GreaterThan(String value) {
            addCriterion("u1 >", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1GreaterThanOrEqualTo(String value) {
            addCriterion("u1 >=", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1LessThan(String value) {
            addCriterion("u1 <", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1LessThanOrEqualTo(String value) {
            addCriterion("u1 <=", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1Like(String value) {
            addCriterion("u1 like", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1NotLike(String value) {
            addCriterion("u1 not like", value, "u1");
            return (Criteria) this;
        }

        public Criteria andU1In(List<String> values) {
            addCriterion("u1 in", values, "u1");
            return (Criteria) this;
        }

        public Criteria andU1NotIn(List<String> values) {
            addCriterion("u1 not in", values, "u1");
            return (Criteria) this;
        }

        public Criteria andU1Between(String value1, String value2) {
            addCriterion("u1 between", value1, value2, "u1");
            return (Criteria) this;
        }

        public Criteria andU1NotBetween(String value1, String value2) {
            addCriterion("u1 not between", value1, value2, "u1");
            return (Criteria) this;
        }

        public Criteria andU2IsNull() {
            addCriterion("u2 is null");
            return (Criteria) this;
        }

        public Criteria andU2IsNotNull() {
            addCriterion("u2 is not null");
            return (Criteria) this;
        }

        public Criteria andU2EqualTo(String value) {
            addCriterion("u2 =", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2NotEqualTo(String value) {
            addCriterion("u2 <>", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2GreaterThan(String value) {
            addCriterion("u2 >", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2GreaterThanOrEqualTo(String value) {
            addCriterion("u2 >=", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2LessThan(String value) {
            addCriterion("u2 <", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2LessThanOrEqualTo(String value) {
            addCriterion("u2 <=", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2Like(String value) {
            addCriterion("u2 like", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2NotLike(String value) {
            addCriterion("u2 not like", value, "u2");
            return (Criteria) this;
        }

        public Criteria andU2In(List<String> values) {
            addCriterion("u2 in", values, "u2");
            return (Criteria) this;
        }

        public Criteria andU2NotIn(List<String> values) {
            addCriterion("u2 not in", values, "u2");
            return (Criteria) this;
        }

        public Criteria andU2Between(String value1, String value2) {
            addCriterion("u2 between", value1, value2, "u2");
            return (Criteria) this;
        }

        public Criteria andU2NotBetween(String value1, String value2) {
            addCriterion("u2 not between", value1, value2, "u2");
            return (Criteria) this;
        }

        public Criteria andSvalueIsNull() {
            addCriterion("svalue is null");
            return (Criteria) this;
        }

        public Criteria andSvalueIsNotNull() {
            addCriterion("svalue is not null");
            return (Criteria) this;
        }

        public Criteria andSvalueEqualTo(String value) {
            addCriterion("svalue =", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueNotEqualTo(String value) {
            addCriterion("svalue <>", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueGreaterThan(String value) {
            addCriterion("svalue >", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueGreaterThanOrEqualTo(String value) {
            addCriterion("svalue >=", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueLessThan(String value) {
            addCriterion("svalue <", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueLessThanOrEqualTo(String value) {
            addCriterion("svalue <=", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueLike(String value) {
            addCriterion("svalue like", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueNotLike(String value) {
            addCriterion("svalue not like", value, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueIn(List<String> values) {
            addCriterion("svalue in", values, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueNotIn(List<String> values) {
            addCriterion("svalue not in", values, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueBetween(String value1, String value2) {
            addCriterion("svalue between", value1, value2, "svalue");
            return (Criteria) this;
        }

        public Criteria andSvalueNotBetween(String value1, String value2) {
            addCriterion("svalue not between", value1, value2, "svalue");
            return (Criteria) this;
        }

        public Criteria andTrustIsNull() {
            addCriterion("trust is null");
            return (Criteria) this;
        }

        public Criteria andTrustIsNotNull() {
            addCriterion("trust is not null");
            return (Criteria) this;
        }

        public Criteria andTrustEqualTo(String value) {
            addCriterion("trust =", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustNotEqualTo(String value) {
            addCriterion("trust <>", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustGreaterThan(String value) {
            addCriterion("trust >", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustGreaterThanOrEqualTo(String value) {
            addCriterion("trust >=", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustLessThan(String value) {
            addCriterion("trust <", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustLessThanOrEqualTo(String value) {
            addCriterion("trust <=", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustLike(String value) {
            addCriterion("trust like", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustNotLike(String value) {
            addCriterion("trust not like", value, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustIn(List<String> values) {
            addCriterion("trust in", values, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustNotIn(List<String> values) {
            addCriterion("trust not in", values, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustBetween(String value1, String value2) {
            addCriterion("trust between", value1, value2, "trust");
            return (Criteria) this;
        }

        public Criteria andTrustNotBetween(String value1, String value2) {
            addCriterion("trust not between", value1, value2, "trust");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andMoneymaxIsNull() {
            addCriterion("moneymax is null");
            return (Criteria) this;
        }

        public Criteria andMoneymaxIsNotNull() {
            addCriterion("moneymax is not null");
            return (Criteria) this;
        }

        public Criteria andMoneymaxEqualTo(String value) {
            addCriterion("moneymax =", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxNotEqualTo(String value) {
            addCriterion("moneymax <>", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxGreaterThan(String value) {
            addCriterion("moneymax >", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxGreaterThanOrEqualTo(String value) {
            addCriterion("moneymax >=", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxLessThan(String value) {
            addCriterion("moneymax <", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxLessThanOrEqualTo(String value) {
            addCriterion("moneymax <=", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxLike(String value) {
            addCriterion("moneymax like", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxNotLike(String value) {
            addCriterion("moneymax not like", value, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxIn(List<String> values) {
            addCriterion("moneymax in", values, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxNotIn(List<String> values) {
            addCriterion("moneymax not in", values, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxBetween(String value1, String value2) {
            addCriterion("moneymax between", value1, value2, "moneymax");
            return (Criteria) this;
        }

        public Criteria andMoneymaxNotBetween(String value1, String value2) {
            addCriterion("moneymax not between", value1, value2, "moneymax");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(String value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(String value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(String value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(String value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(String value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(String value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLike(String value) {
            addCriterion("count like", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotLike(String value) {
            addCriterion("count not like", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<String> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<String> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(String value1, String value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(String value1, String value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socialnet
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}