package tiger.common.dal.persistence.behaviour_authen;

public class All_location_table {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_location_table.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_location_table.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_location_table.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_location_table.user
     *
     * @return the value of all_location_table.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_location_table.user
     *
     * @param user the value for all_location_table.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_location_table.location
     *
     * @return the value of all_location_table.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_location_table.location
     *
     * @param location the value for all_location_table.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_location_table.num
     *
     * @return the value of all_location_table.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_location_table.num
     *
     * @param num the value for all_location_table.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}