package tiger.common.dal.persistence.behaviour_authen;

public class Assist_table {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.weekday_num
     *
     * @mbggenerated
     */
    private Integer weekdayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.weekend_num
     *
     * @mbggenerated
     */
    private Integer weekendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.festival_num
     *
     * @mbggenerated
     */
    private Integer festivalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.normal_day_num
     *
     * @mbggenerated
     */
    private Integer normalDayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.mean_time
     *
     * @mbggenerated
     */
    private Float meanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.var_time
     *
     * @mbggenerated
     */
    private Float varTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.mean_money
     *
     * @mbggenerated
     */
    private Float meanMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.var_money
     *
     * @mbggenerated
     */
    private Float varMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assist_table.total_trade_num
     *
     * @mbggenerated
     */
    private Integer totalTradeNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.user
     *
     * @return the value of assist_table.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.user
     *
     * @param user the value for assist_table.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.weekday_num
     *
     * @return the value of assist_table.weekday_num
     *
     * @mbggenerated
     */
    public Integer getWeekdayNum() {
        return weekdayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.weekday_num
     *
     * @param weekdayNum the value for assist_table.weekday_num
     *
     * @mbggenerated
     */
    public void setWeekdayNum(Integer weekdayNum) {
        this.weekdayNum = weekdayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.weekend_num
     *
     * @return the value of assist_table.weekend_num
     *
     * @mbggenerated
     */
    public Integer getWeekendNum() {
        return weekendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.weekend_num
     *
     * @param weekendNum the value for assist_table.weekend_num
     *
     * @mbggenerated
     */
    public void setWeekendNum(Integer weekendNum) {
        this.weekendNum = weekendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.festival_num
     *
     * @return the value of assist_table.festival_num
     *
     * @mbggenerated
     */
    public Integer getFestivalNum() {
        return festivalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.festival_num
     *
     * @param festivalNum the value for assist_table.festival_num
     *
     * @mbggenerated
     */
    public void setFestivalNum(Integer festivalNum) {
        this.festivalNum = festivalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.normal_day_num
     *
     * @return the value of assist_table.normal_day_num
     *
     * @mbggenerated
     */
    public Integer getNormalDayNum() {
        return normalDayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.normal_day_num
     *
     * @param normalDayNum the value for assist_table.normal_day_num
     *
     * @mbggenerated
     */
    public void setNormalDayNum(Integer normalDayNum) {
        this.normalDayNum = normalDayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.mean_time
     *
     * @return the value of assist_table.mean_time
     *
     * @mbggenerated
     */
    public Float getMeanTime() {
        return meanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.mean_time
     *
     * @param meanTime the value for assist_table.mean_time
     *
     * @mbggenerated
     */
    public void setMeanTime(Float meanTime) {
        this.meanTime = meanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.var_time
     *
     * @return the value of assist_table.var_time
     *
     * @mbggenerated
     */
    public Float getVarTime() {
        return varTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.var_time
     *
     * @param varTime the value for assist_table.var_time
     *
     * @mbggenerated
     */
    public void setVarTime(Float varTime) {
        this.varTime = varTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.mean_money
     *
     * @return the value of assist_table.mean_money
     *
     * @mbggenerated
     */
    public Float getMeanMoney() {
        return meanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.mean_money
     *
     * @param meanMoney the value for assist_table.mean_money
     *
     * @mbggenerated
     */
    public void setMeanMoney(Float meanMoney) {
        this.meanMoney = meanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.var_money
     *
     * @return the value of assist_table.var_money
     *
     * @mbggenerated
     */
    public Float getVarMoney() {
        return varMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.var_money
     *
     * @param varMoney the value for assist_table.var_money
     *
     * @mbggenerated
     */
    public void setVarMoney(Float varMoney) {
        this.varMoney = varMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assist_table.total_trade_num
     *
     * @return the value of assist_table.total_trade_num
     *
     * @mbggenerated
     */
    public Integer getTotalTradeNum() {
        return totalTradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assist_table.total_trade_num
     *
     * @param totalTradeNum the value for assist_table.total_trade_num
     *
     * @mbggenerated
     */
    public void setTotalTradeNum(Integer totalTradeNum) {
        this.totalTradeNum = totalTradeNum;
    }
}