package tiger.common.dal.persistence.behaviour_authen;

import java.util.Date;

public class Behavior_certificate_table {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.weekday
     *
     * @mbggenerated
     */
    private Float weekday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.weekend
     *
     * @mbggenerated
     */
    private Float weekend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.festival
     *
     * @mbggenerated
     */
    private Float festival;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.normal_day
     *
     * @mbggenerated
     */
    private Float normalDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.interval_1
     *
     * @mbggenerated
     */
    private Float interval1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.interval_2
     *
     * @mbggenerated
     */
    private Float interval2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.interval_3
     *
     * @mbggenerated
     */
    private Float interval3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.interval_4
     *
     * @mbggenerated
     */
    private Float interval4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.location
     *
     * @mbggenerated
     */
    private Float location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.range_1
     *
     * @mbggenerated
     */
    private Float range1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.range_2
     *
     * @mbggenerated
     */
    private Float range2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.range_3
     *
     * @mbggenerated
     */
    private Float range3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.range_4
     *
     * @mbggenerated
     */
    private Float range4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behavior_certificate_table.last_trade_time
     *
     * @mbggenerated
     */
    private Date lastTradeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.user
     *
     * @return the value of behavior_certificate_table.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.user
     *
     * @param user the value for behavior_certificate_table.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.weekday
     *
     * @return the value of behavior_certificate_table.weekday
     *
     * @mbggenerated
     */
    public Float getWeekday() {
        return weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.weekday
     *
     * @param weekday the value for behavior_certificate_table.weekday
     *
     * @mbggenerated
     */
    public void setWeekday(Float weekday) {
        this.weekday = weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.weekend
     *
     * @return the value of behavior_certificate_table.weekend
     *
     * @mbggenerated
     */
    public Float getWeekend() {
        return weekend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.weekend
     *
     * @param weekend the value for behavior_certificate_table.weekend
     *
     * @mbggenerated
     */
    public void setWeekend(Float weekend) {
        this.weekend = weekend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.festival
     *
     * @return the value of behavior_certificate_table.festival
     *
     * @mbggenerated
     */
    public Float getFestival() {
        return festival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.festival
     *
     * @param festival the value for behavior_certificate_table.festival
     *
     * @mbggenerated
     */
    public void setFestival(Float festival) {
        this.festival = festival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.normal_day
     *
     * @return the value of behavior_certificate_table.normal_day
     *
     * @mbggenerated
     */
    public Float getNormalDay() {
        return normalDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.normal_day
     *
     * @param normalDay the value for behavior_certificate_table.normal_day
     *
     * @mbggenerated
     */
    public void setNormalDay(Float normalDay) {
        this.normalDay = normalDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.interval_1
     *
     * @return the value of behavior_certificate_table.interval_1
     *
     * @mbggenerated
     */
    public Float getInterval1() {
        return interval1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.interval_1
     *
     * @param interval1 the value for behavior_certificate_table.interval_1
     *
     * @mbggenerated
     */
    public void setInterval1(Float interval1) {
        this.interval1 = interval1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.interval_2
     *
     * @return the value of behavior_certificate_table.interval_2
     *
     * @mbggenerated
     */
    public Float getInterval2() {
        return interval2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.interval_2
     *
     * @param interval2 the value for behavior_certificate_table.interval_2
     *
     * @mbggenerated
     */
    public void setInterval2(Float interval2) {
        this.interval2 = interval2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.interval_3
     *
     * @return the value of behavior_certificate_table.interval_3
     *
     * @mbggenerated
     */
    public Float getInterval3() {
        return interval3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.interval_3
     *
     * @param interval3 the value for behavior_certificate_table.interval_3
     *
     * @mbggenerated
     */
    public void setInterval3(Float interval3) {
        this.interval3 = interval3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.interval_4
     *
     * @return the value of behavior_certificate_table.interval_4
     *
     * @mbggenerated
     */
    public Float getInterval4() {
        return interval4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.interval_4
     *
     * @param interval4 the value for behavior_certificate_table.interval_4
     *
     * @mbggenerated
     */
    public void setInterval4(Float interval4) {
        this.interval4 = interval4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.location
     *
     * @return the value of behavior_certificate_table.location
     *
     * @mbggenerated
     */
    public Float getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.location
     *
     * @param location the value for behavior_certificate_table.location
     *
     * @mbggenerated
     */
    public void setLocation(Float location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.range_1
     *
     * @return the value of behavior_certificate_table.range_1
     *
     * @mbggenerated
     */
    public Float getRange1() {
        return range1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.range_1
     *
     * @param range1 the value for behavior_certificate_table.range_1
     *
     * @mbggenerated
     */
    public void setRange1(Float range1) {
        this.range1 = range1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.range_2
     *
     * @return the value of behavior_certificate_table.range_2
     *
     * @mbggenerated
     */
    public Float getRange2() {
        return range2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.range_2
     *
     * @param range2 the value for behavior_certificate_table.range_2
     *
     * @mbggenerated
     */
    public void setRange2(Float range2) {
        this.range2 = range2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.range_3
     *
     * @return the value of behavior_certificate_table.range_3
     *
     * @mbggenerated
     */
    public Float getRange3() {
        return range3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.range_3
     *
     * @param range3 the value for behavior_certificate_table.range_3
     *
     * @mbggenerated
     */
    public void setRange3(Float range3) {
        this.range3 = range3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.range_4
     *
     * @return the value of behavior_certificate_table.range_4
     *
     * @mbggenerated
     */
    public Float getRange4() {
        return range4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.range_4
     *
     * @param range4 the value for behavior_certificate_table.range_4
     *
     * @mbggenerated
     */
    public void setRange4(Float range4) {
        this.range4 = range4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behavior_certificate_table.last_trade_time
     *
     * @return the value of behavior_certificate_table.last_trade_time
     *
     * @mbggenerated
     */
    public Date getLastTradeTime() {
        return lastTradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behavior_certificate_table.last_trade_time
     *
     * @param lastTradeTime the value for behavior_certificate_table.last_trade_time
     *
     * @mbggenerated
     */
    public void setLastTradeTime(Date lastTradeTime) {
        this.lastTradeTime = lastTradeTime;
    }
}