package tiger.common.dal.persistence.behaviour_authen;

public class Card_table {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_table.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_table.TICN
     *
     * @mbggenerated
     */
    private String ticn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_table.user
     *
     * @return the value of card_table.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_table.user
     *
     * @param user the value for card_table.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_table.TICN
     *
     * @return the value of card_table.TICN
     *
     * @mbggenerated
     */
    public String getTicn() {
        return ticn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_table.TICN
     *
     * @param ticn the value for card_table.TICN
     *
     * @mbggenerated
     */
    public void setTicn(String ticn) {
        this.ticn = ticn == null ? null : ticn.trim();
    }
}