package tiger.common.dal.persistence.behaviour_authen;

import java.util.Date;

public class Simulation_source_tableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Time_Stamp
     *
     * @mbggenerated
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Time_Stamp
     *
     * @return the value of simulation_source_table.Time_Stamp
     *
     * @mbggenerated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Time_Stamp
     *
     * @param timeStamp the value for simulation_source_table.Time_Stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.user
     *
     * @return the value of simulation_source_table.user
     *
     * @mbggenerated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.user
     *
     * @param user the value for simulation_source_table.user
     *
     * @mbggenerated
     */
    public void setUser(Integer user) {
        this.user = user;
    }
}