package tiger.common.dal.persistence.behaviour_authen;

import java.math.BigDecimal;
import java.util.Date;

public class Simulation_source_table extends Simulation_source_tableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Tran_Out_Card_Num
     *
     * @mbggenerated
     */
    private String tranOutCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Tx_Amt
     *
     * @mbggenerated
     */
    private BigDecimal txAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Tran_In_Acct_Num
     *
     * @mbggenerated
     */
    private String tranInAcctNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Jnl_Seq_Num
     *
     * @mbggenerated
     */
    private String jnlSeqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Event_Dt
     *
     * @mbggenerated
     */
    private Date eventDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Lable
     *
     * @mbggenerated
     */
    private Boolean lable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Zone_Num
     *
     * @mbggenerated
     */
    private String zoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simulation_source_table.Predication_result
     *
     * @mbggenerated
     */
    private Boolean predicationResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Tran_Out_Card_Num
     *
     * @return the value of simulation_source_table.Tran_Out_Card_Num
     *
     * @mbggenerated
     */
    public String getTranOutCardNum() {
        return tranOutCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Tran_Out_Card_Num
     *
     * @param tranOutCardNum the value for simulation_source_table.Tran_Out_Card_Num
     *
     * @mbggenerated
     */
    public void setTranOutCardNum(String tranOutCardNum) {
        this.tranOutCardNum = tranOutCardNum == null ? null : tranOutCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Tx_Amt
     *
     * @return the value of simulation_source_table.Tx_Amt
     *
     * @mbggenerated
     */
    public BigDecimal getTxAmt() {
        return txAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Tx_Amt
     *
     * @param txAmt the value for simulation_source_table.Tx_Amt
     *
     * @mbggenerated
     */
    public void setTxAmt(BigDecimal txAmt) {
        this.txAmt = txAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Tran_In_Acct_Num
     *
     * @return the value of simulation_source_table.Tran_In_Acct_Num
     *
     * @mbggenerated
     */
    public String getTranInAcctNum() {
        return tranInAcctNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Tran_In_Acct_Num
     *
     * @param tranInAcctNum the value for simulation_source_table.Tran_In_Acct_Num
     *
     * @mbggenerated
     */
    public void setTranInAcctNum(String tranInAcctNum) {
        this.tranInAcctNum = tranInAcctNum == null ? null : tranInAcctNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Jnl_Seq_Num
     *
     * @return the value of simulation_source_table.Jnl_Seq_Num
     *
     * @mbggenerated
     */
    public String getJnlSeqNum() {
        return jnlSeqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Jnl_Seq_Num
     *
     * @param jnlSeqNum the value for simulation_source_table.Jnl_Seq_Num
     *
     * @mbggenerated
     */
    public void setJnlSeqNum(String jnlSeqNum) {
        this.jnlSeqNum = jnlSeqNum == null ? null : jnlSeqNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Event_Dt
     *
     * @return the value of simulation_source_table.Event_Dt
     *
     * @mbggenerated
     */
    public Date getEventDt() {
        return eventDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Event_Dt
     *
     * @param eventDt the value for simulation_source_table.Event_Dt
     *
     * @mbggenerated
     */
    public void setEventDt(Date eventDt) {
        this.eventDt = eventDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Lable
     *
     * @return the value of simulation_source_table.Lable
     *
     * @mbggenerated
     */
    public Boolean getLable() {
        return lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Lable
     *
     * @param lable the value for simulation_source_table.Lable
     *
     * @mbggenerated
     */
    public void setLable(Boolean lable) {
        this.lable = lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Zone_Num
     *
     * @return the value of simulation_source_table.Zone_Num
     *
     * @mbggenerated
     */
    public String getZoneNum() {
        return zoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Zone_Num
     *
     * @param zoneNum the value for simulation_source_table.Zone_Num
     *
     * @mbggenerated
     */
    public void setZoneNum(String zoneNum) {
        this.zoneNum = zoneNum == null ? null : zoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simulation_source_table.Predication_result
     *
     * @return the value of simulation_source_table.Predication_result
     *
     * @mbggenerated
     */
    public Boolean getPredicationResult() {
        return predicationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simulation_source_table.Predication_result
     *
     * @param predicationResult the value for simulation_source_table.Predication_result
     *
     * @mbggenerated
     */
    public void setPredicationResult(Boolean predicationResult) {
        this.predicationResult = predicationResult;
    }
}