package tiger.common.dal.persistence.mapper;

import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.behaviour_authen.Assist_table;
import tiger.common.dal.persistence.behaviour_authen.Assist_tableExample;

import java.util.List;

public interface Assist_tableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int countByExample(Assist_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int deleteByExample(Assist_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int insert(Assist_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int insertSelective(Assist_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    List<Assist_table> selectByExample(Assist_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    Assist_table selectByPrimaryKey(Integer user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Assist_table record, @Param("example") Assist_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Assist_table record, @Param("example") Assist_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Assist_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assist_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Assist_table record);
}