package tiger.common.dal.persistence.mapper;

import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.behaviour_authen.Behavior_certificate_table;
import tiger.common.dal.persistence.behaviour_authen.Behavior_certificate_tableExample;

import java.util.List;

public interface Behavior_certificate_tableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int countByExample(Behavior_certificate_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int deleteByExample(Behavior_certificate_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int insert(Behavior_certificate_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int insertSelective(Behavior_certificate_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    List<Behavior_certificate_table> selectByExample(Behavior_certificate_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    Behavior_certificate_table selectByPrimaryKey(Integer user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Behavior_certificate_table record, @Param("example") Behavior_certificate_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Behavior_certificate_table record, @Param("example") Behavior_certificate_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Behavior_certificate_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behavior_certificate_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Behavior_certificate_table record);
}