package tiger.common.dal.persistence.mapper;

import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.behaviour_authen.Card_table;
import tiger.common.dal.persistence.behaviour_authen.Card_tableExample;

import java.util.List;

public interface Card_tableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int countByExample(Card_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int deleteByExample(Card_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int insert(Card_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int insertSelective(Card_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    List<Card_table> selectByExample(Card_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    Card_table selectByPrimaryKey(Integer user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Card_table record, @Param("example") Card_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Card_table record, @Param("example") Card_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Card_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Card_table record);
}