package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.icbc.CustomerInfoDO;
import tiger.common.dal.persistence.icbc.CustomerInfoDOExample;

public interface CustomerInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int countByExample(CustomerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int insert(CustomerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int insertSelective(CustomerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    List<CustomerInfoDO> selectByExample(CustomerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    CustomerInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerInfoDO record, @Param("example") CustomerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerInfoDO record, @Param("example") CustomerInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerInfoDO record);

    /**
     * 获得所有的客户信息
     * @return
     */
    List<CustomerInfoDO> selectAll();
}