package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.icbc.EquipmentInfoDO;
import tiger.common.dal.persistence.icbc.EquipmentInfoDOExample;

public interface EquipmentInfoDOMapper {
    /**
     * 获得所有的设备信息
     * @return
     */
    List<EquipmentInfoDO> selectAll();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int countByExample(EquipmentInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int deleteByExample(EquipmentInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int insert(EquipmentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int insertSelective(EquipmentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    List<EquipmentInfoDO> selectByExample(EquipmentInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    EquipmentInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EquipmentInfoDO record, @Param("example") EquipmentInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EquipmentInfoDO record, @Param("example") EquipmentInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EquipmentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipmentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EquipmentInfoDO record);
}