package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.icbc.LoginInfoDO;
import tiger.common.dal.persistence.icbc.LoginInfoDOExample;

public interface LoginInfoDOMapper {
    /**
     * 获得所有的登陆信息
     * @return
     */
    List<LoginInfoDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int countByExample(LoginInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int deleteByExample(LoginInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int insert(LoginInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int insertSelective(LoginInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    List<LoginInfoDO> selectByExample(LoginInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    LoginInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LoginInfoDO record, @Param("example") LoginInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LoginInfoDO record, @Param("example") LoginInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoginInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoginInfoDO record);
}