package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.icbc.RegisterInfoDO;
import tiger.common.dal.persistence.icbc.RegisterInfoDOExample;

public interface RegisterInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int countByExample(RegisterInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int deleteByExample(RegisterInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int insert(RegisterInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int insertSelective(RegisterInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    List<RegisterInfoDO> selectByExample(RegisterInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    RegisterInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RegisterInfoDO record, @Param("example") RegisterInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RegisterInfoDO record, @Param("example") RegisterInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RegisterInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RegisterInfoDO record);
}