package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.results.Results;
import tiger.common.dal.persistence.results.ResultsExample;

public interface ResultsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int countByExample(ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int deleteByExample(ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int insert(Results record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int insertSelective(Results record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    List<Results> selectByExample(ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    Results selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Results record, @Param("example") ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Results record, @Param("example") ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Results record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Results record);
}