package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.icbc.RulesDO;
import tiger.common.dal.persistence.icbc.RulesDOExample;

public interface RulesDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int countByExample(RulesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int deleteByExample(RulesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int insert(RulesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int insertSelective(RulesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    List<RulesDO> selectByExample(RulesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    RulesDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RulesDO record, @Param("example") RulesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RulesDO record, @Param("example") RulesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RulesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RulesDO record);
}