package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.icbc.SelectedAndroidDO;
import tiger.common.dal.persistence.icbc.SelectedAndroidDOExample;

public interface SelectedAndroidDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int countByExample(SelectedAndroidDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int deleteByExample(SelectedAndroidDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int insert(SelectedAndroidDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int insertSelective(SelectedAndroidDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    List<SelectedAndroidDO> selectByExample(SelectedAndroidDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    SelectedAndroidDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SelectedAndroidDO record, @Param("example") SelectedAndroidDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SelectedAndroidDO record, @Param("example") SelectedAndroidDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SelectedAndroidDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SelectedAndroidDO record);
}