package tiger.common.dal.persistence.mapper;

import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.behaviour_authen.Simulation_source_table;
import tiger.common.dal.persistence.behaviour_authen.Simulation_source_tableExample;
import tiger.common.dal.persistence.behaviour_authen.Simulation_source_tableKey;

import java.util.List;

public interface Simulation_source_tableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int countByExample(Simulation_source_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int deleteByExample(Simulation_source_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Simulation_source_tableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int insert(Simulation_source_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int insertSelective(Simulation_source_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    List<Simulation_source_table> selectByExample(Simulation_source_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    Simulation_source_table selectByPrimaryKey(Simulation_source_tableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Simulation_source_table record, @Param("example") Simulation_source_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Simulation_source_table record, @Param("example") Simulation_source_tableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Simulation_source_table record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simulation_source_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Simulation_source_table record);
}