package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.socialnet.Socialnet;
import tiger.common.dal.persistence.socialnet.SocialnetExample;

public interface SocialnetMapper {
    /**
     * 获取 u1 转账给 u2 的交易信任值
     */
    int selectTrust(String user1, String user2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int countByExample(SocialnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int deleteByExample(SocialnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long dealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int insert(Socialnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int insertSelective(Socialnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    List<Socialnet> selectByExample(SocialnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    Socialnet selectByPrimaryKey(Long dealid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Socialnet record, @Param("example") SocialnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Socialnet record, @Param("example") SocialnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Socialnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socialnet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Socialnet record);

}