package tiger.common.dal.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tiger.common.dal.persistence.icbc.TransactioninfocountDO;
import tiger.common.dal.persistence.icbc.TransactioninfocountDOExample;

public interface TransactioninfocountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactioninfocount
     *
     * @mbggenerated
     */
    int countByExample(TransactioninfocountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactioninfocount
     *
     * @mbggenerated
     */
    int deleteByExample(TransactioninfocountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactioninfocount
     *
     * @mbggenerated
     */
    int insert(TransactioninfocountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactioninfocount
     *
     * @mbggenerated
     */
    int insertSelective(TransactioninfocountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactioninfocount
     *
     * @mbggenerated
     */
    List<TransactioninfocountDO> selectByExample(TransactioninfocountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactioninfocount
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TransactioninfocountDO record, @Param("example") TransactioninfocountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transactioninfocount
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TransactioninfocountDO record, @Param("example") TransactioninfocountDOExample example);


}