package tiger.common.dal.persistence.materials;

public class Materials {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.majorcategory
     *
     * @mbggenerated
     */
    private String majorcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.subcategory
     *
     * @mbggenerated
     */
    private String subcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.detailclass
     *
     * @mbggenerated
     */
    private String detailclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.productline
     *
     * @mbggenerated
     */
    private String productline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.marketprice
     *
     * @mbggenerated
     */
    private Double marketprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.discount
     *
     * @mbggenerated
     */
    private Double discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.id
     *
     * @return the value of materials.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.id
     *
     * @param id the value for materials.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.name
     *
     * @return the value of materials.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.name
     *
     * @param name the value for materials.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.code
     *
     * @return the value of materials.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.code
     *
     * @param code the value for materials.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.description
     *
     * @return the value of materials.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.description
     *
     * @param description the value for materials.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.majorcategory
     *
     * @return the value of materials.majorcategory
     *
     * @mbggenerated
     */
    public String getMajorcategory() {
        return majorcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.majorcategory
     *
     * @param majorcategory the value for materials.majorcategory
     *
     * @mbggenerated
     */
    public void setMajorcategory(String majorcategory) {
        this.majorcategory = majorcategory == null ? null : majorcategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.subcategory
     *
     * @return the value of materials.subcategory
     *
     * @mbggenerated
     */
    public String getSubcategory() {
        return subcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.subcategory
     *
     * @param subcategory the value for materials.subcategory
     *
     * @mbggenerated
     */
    public void setSubcategory(String subcategory) {
        this.subcategory = subcategory == null ? null : subcategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.detailclass
     *
     * @return the value of materials.detailclass
     *
     * @mbggenerated
     */
    public String getDetailclass() {
        return detailclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.detailclass
     *
     * @param detailclass the value for materials.detailclass
     *
     * @mbggenerated
     */
    public void setDetailclass(String detailclass) {
        this.detailclass = detailclass == null ? null : detailclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.company
     *
     * @return the value of materials.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.company
     *
     * @param company the value for materials.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.productline
     *
     * @return the value of materials.productline
     *
     * @mbggenerated
     */
    public String getProductline() {
        return productline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.productline
     *
     * @param productline the value for materials.productline
     *
     * @mbggenerated
     */
    public void setProductline(String productline) {
        this.productline = productline == null ? null : productline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.marketprice
     *
     * @return the value of materials.marketprice
     *
     * @mbggenerated
     */
    public Double getMarketprice() {
        return marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.marketprice
     *
     * @param marketprice the value for materials.marketprice
     *
     * @mbggenerated
     */
    public void setMarketprice(Double marketprice) {
        this.marketprice = marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.discount
     *
     * @return the value of materials.discount
     *
     * @mbggenerated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.discount
     *
     * @param discount the value for materials.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials.remarks
     *
     * @return the value of materials.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials.remarks
     *
     * @param remarks the value for materials.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}