package tiger.common.dal.persistence.icbc;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LoginInfoDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public LoginInfoDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNull() {
            addCriterion("Event_Id is null");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("Event_Id is not null");
            return (Criteria) this;
        }

        public Criteria andEventIdEqualTo(String value) {
            addCriterion("Event_Id =", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotEqualTo(String value) {
            addCriterion("Event_Id <>", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThan(String value) {
            addCriterion("Event_Id >", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(String value) {
            addCriterion("Event_Id >=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThan(String value) {
            addCriterion("Event_Id <", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThanOrEqualTo(String value) {
            addCriterion("Event_Id <=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLike(String value) {
            addCriterion("Event_Id like", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotLike(String value) {
            addCriterion("Event_Id not like", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdIn(List<String> values) {
            addCriterion("Event_Id in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotIn(List<String> values) {
            addCriterion("Event_Id not in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdBetween(String value1, String value2) {
            addCriterion("Event_Id between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotBetween(String value1, String value2) {
            addCriterion("Event_Id not between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumIsNull() {
            addCriterion("Jnl_Seq_Num is null");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumIsNotNull() {
            addCriterion("Jnl_Seq_Num is not null");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumEqualTo(String value) {
            addCriterion("Jnl_Seq_Num =", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumNotEqualTo(String value) {
            addCriterion("Jnl_Seq_Num <>", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumGreaterThan(String value) {
            addCriterion("Jnl_Seq_Num >", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumGreaterThanOrEqualTo(String value) {
            addCriterion("Jnl_Seq_Num >=", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumLessThan(String value) {
            addCriterion("Jnl_Seq_Num <", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumLessThanOrEqualTo(String value) {
            addCriterion("Jnl_Seq_Num <=", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumLike(String value) {
            addCriterion("Jnl_Seq_Num like", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumNotLike(String value) {
            addCriterion("Jnl_Seq_Num not like", value, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumIn(List<String> values) {
            addCriterion("Jnl_Seq_Num in", values, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumNotIn(List<String> values) {
            addCriterion("Jnl_Seq_Num not in", values, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumBetween(String value1, String value2) {
            addCriterion("Jnl_Seq_Num between", value1, value2, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andJnlSeqNumNotBetween(String value1, String value2) {
            addCriterion("Jnl_Seq_Num not between", value1, value2, "jnlSeqNum");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdIsNull() {
            addCriterion("Chan_Idtfy_Id is null");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdIsNotNull() {
            addCriterion("Chan_Idtfy_Id is not null");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdEqualTo(String value) {
            addCriterion("Chan_Idtfy_Id =", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdNotEqualTo(String value) {
            addCriterion("Chan_Idtfy_Id <>", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdGreaterThan(String value) {
            addCriterion("Chan_Idtfy_Id >", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdGreaterThanOrEqualTo(String value) {
            addCriterion("Chan_Idtfy_Id >=", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdLessThan(String value) {
            addCriterion("Chan_Idtfy_Id <", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdLessThanOrEqualTo(String value) {
            addCriterion("Chan_Idtfy_Id <=", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdLike(String value) {
            addCriterion("Chan_Idtfy_Id like", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdNotLike(String value) {
            addCriterion("Chan_Idtfy_Id not like", value, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdIn(List<String> values) {
            addCriterion("Chan_Idtfy_Id in", values, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdNotIn(List<String> values) {
            addCriterion("Chan_Idtfy_Id not in", values, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdBetween(String value1, String value2) {
            addCriterion("Chan_Idtfy_Id between", value1, value2, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andChanIdtfyIdNotBetween(String value1, String value2) {
            addCriterion("Chan_Idtfy_Id not between", value1, value2, "chanIdtfyId");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdIsNull() {
            addCriterion("Webbank_Tx_Cd is null");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdIsNotNull() {
            addCriterion("Webbank_Tx_Cd is not null");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdEqualTo(String value) {
            addCriterion("Webbank_Tx_Cd =", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdNotEqualTo(String value) {
            addCriterion("Webbank_Tx_Cd <>", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdGreaterThan(String value) {
            addCriterion("Webbank_Tx_Cd >", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdGreaterThanOrEqualTo(String value) {
            addCriterion("Webbank_Tx_Cd >=", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdLessThan(String value) {
            addCriterion("Webbank_Tx_Cd <", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdLessThanOrEqualTo(String value) {
            addCriterion("Webbank_Tx_Cd <=", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdLike(String value) {
            addCriterion("Webbank_Tx_Cd like", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdNotLike(String value) {
            addCriterion("Webbank_Tx_Cd not like", value, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdIn(List<String> values) {
            addCriterion("Webbank_Tx_Cd in", values, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdNotIn(List<String> values) {
            addCriterion("Webbank_Tx_Cd not in", values, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdBetween(String value1, String value2) {
            addCriterion("Webbank_Tx_Cd between", value1, value2, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxCdNotBetween(String value1, String value2) {
            addCriterion("Webbank_Tx_Cd not between", value1, value2, "webbankTxCd");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameIsNull() {
            addCriterion("Webbank_Tx_Name is null");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameIsNotNull() {
            addCriterion("Webbank_Tx_Name is not null");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameEqualTo(String value) {
            addCriterion("Webbank_Tx_Name =", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameNotEqualTo(String value) {
            addCriterion("Webbank_Tx_Name <>", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameGreaterThan(String value) {
            addCriterion("Webbank_Tx_Name >", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameGreaterThanOrEqualTo(String value) {
            addCriterion("Webbank_Tx_Name >=", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameLessThan(String value) {
            addCriterion("Webbank_Tx_Name <", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameLessThanOrEqualTo(String value) {
            addCriterion("Webbank_Tx_Name <=", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameLike(String value) {
            addCriterion("Webbank_Tx_Name like", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameNotLike(String value) {
            addCriterion("Webbank_Tx_Name not like", value, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameIn(List<String> values) {
            addCriterion("Webbank_Tx_Name in", values, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameNotIn(List<String> values) {
            addCriterion("Webbank_Tx_Name not in", values, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameBetween(String value1, String value2) {
            addCriterion("Webbank_Tx_Name between", value1, value2, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andWebbankTxNameNotBetween(String value1, String value2) {
            addCriterion("Webbank_Tx_Name not between", value1, value2, "webbankTxName");
            return (Criteria) this;
        }

        public Criteria andJnlDtIsNull() {
            addCriterion("Jnl_Dt is null");
            return (Criteria) this;
        }

        public Criteria andJnlDtIsNotNull() {
            addCriterion("Jnl_Dt is not null");
            return (Criteria) this;
        }

        public Criteria andJnlDtEqualTo(Date value) {
            addCriterionForJDBCDate("Jnl_Dt =", value, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("Jnl_Dt <>", value, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtGreaterThan(Date value) {
            addCriterionForJDBCDate("Jnl_Dt >", value, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Jnl_Dt >=", value, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtLessThan(Date value) {
            addCriterionForJDBCDate("Jnl_Dt <", value, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Jnl_Dt <=", value, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtIn(List<Date> values) {
            addCriterionForJDBCDate("Jnl_Dt in", values, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("Jnl_Dt not in", values, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Jnl_Dt between", value1, value2, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Jnl_Dt not between", value1, value2, "jnlDt");
            return (Criteria) this;
        }

        public Criteria andJnlTmIsNull() {
            addCriterion("Jnl_Tm is null");
            return (Criteria) this;
        }

        public Criteria andJnlTmIsNotNull() {
            addCriterion("Jnl_Tm is not null");
            return (Criteria) this;
        }

        public Criteria andJnlTmEqualTo(String value) {
            addCriterion("Jnl_Tm =", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmNotEqualTo(String value) {
            addCriterion("Jnl_Tm <>", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmGreaterThan(String value) {
            addCriterion("Jnl_Tm >", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmGreaterThanOrEqualTo(String value) {
            addCriterion("Jnl_Tm >=", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmLessThan(String value) {
            addCriterion("Jnl_Tm <", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmLessThanOrEqualTo(String value) {
            addCriterion("Jnl_Tm <=", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmLike(String value) {
            addCriterion("Jnl_Tm like", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmNotLike(String value) {
            addCriterion("Jnl_Tm not like", value, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmIn(List<String> values) {
            addCriterion("Jnl_Tm in", values, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmNotIn(List<String> values) {
            addCriterion("Jnl_Tm not in", values, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmBetween(String value1, String value2) {
            addCriterion("Jnl_Tm between", value1, value2, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andJnlTmNotBetween(String value1, String value2) {
            addCriterion("Jnl_Tm not between", value1, value2, "jnlTm");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameIsNull() {
            addCriterion("Tx_Intfc_Name is null");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameIsNotNull() {
            addCriterion("Tx_Intfc_Name is not null");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameEqualTo(String value) {
            addCriterion("Tx_Intfc_Name =", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameNotEqualTo(String value) {
            addCriterion("Tx_Intfc_Name <>", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameGreaterThan(String value) {
            addCriterion("Tx_Intfc_Name >", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameGreaterThanOrEqualTo(String value) {
            addCriterion("Tx_Intfc_Name >=", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameLessThan(String value) {
            addCriterion("Tx_Intfc_Name <", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameLessThanOrEqualTo(String value) {
            addCriterion("Tx_Intfc_Name <=", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameLike(String value) {
            addCriterion("Tx_Intfc_Name like", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameNotLike(String value) {
            addCriterion("Tx_Intfc_Name not like", value, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameIn(List<String> values) {
            addCriterion("Tx_Intfc_Name in", values, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameNotIn(List<String> values) {
            addCriterion("Tx_Intfc_Name not in", values, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameBetween(String value1, String value2) {
            addCriterion("Tx_Intfc_Name between", value1, value2, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andTxIntfcNameNotBetween(String value1, String value2) {
            addCriterion("Tx_Intfc_Name not between", value1, value2, "txIntfcName");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeIsNull() {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode is null");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeIsNotNull() {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode is not null");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeEqualTo(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode =", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeNotEqualTo(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode <>", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeGreaterThan(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode >", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeGreaterThanOrEqualTo(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode >=", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeLessThan(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode <", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeLessThanOrEqualTo(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode <=", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeLike(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode like", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeNotLike(String value) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode not like", value, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeIn(List<String> values) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode in", values, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeNotIn(List<String> values) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode not in", values, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeBetween(String value1, String value2) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode between", value1, value2, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andIndvWbankGatewayRespEncodeNotBetween(String value1, String value2) {
            addCriterion("Indv_Wbank_Gateway_Resp_Encode not between", value1, value2, "indvWbankGatewayRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeIsNull() {
            addCriterion("Host_Online_Resp_Encode is null");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeIsNotNull() {
            addCriterion("Host_Online_Resp_Encode is not null");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeEqualTo(String value) {
            addCriterion("Host_Online_Resp_Encode =", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeNotEqualTo(String value) {
            addCriterion("Host_Online_Resp_Encode <>", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeGreaterThan(String value) {
            addCriterion("Host_Online_Resp_Encode >", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeGreaterThanOrEqualTo(String value) {
            addCriterion("Host_Online_Resp_Encode >=", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeLessThan(String value) {
            addCriterion("Host_Online_Resp_Encode <", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeLessThanOrEqualTo(String value) {
            addCriterion("Host_Online_Resp_Encode <=", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeLike(String value) {
            addCriterion("Host_Online_Resp_Encode like", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeNotLike(String value) {
            addCriterion("Host_Online_Resp_Encode not like", value, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeIn(List<String> values) {
            addCriterion("Host_Online_Resp_Encode in", values, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeNotIn(List<String> values) {
            addCriterion("Host_Online_Resp_Encode not in", values, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeBetween(String value1, String value2) {
            addCriterion("Host_Online_Resp_Encode between", value1, value2, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andHostOnlineRespEncodeNotBetween(String value1, String value2) {
            addCriterion("Host_Online_Resp_Encode not between", value1, value2, "hostOnlineRespEncode");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdIsNull() {
            addCriterion("Ebank_Err_Cd is null");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdIsNotNull() {
            addCriterion("Ebank_Err_Cd is not null");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdEqualTo(String value) {
            addCriterion("Ebank_Err_Cd =", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdNotEqualTo(String value) {
            addCriterion("Ebank_Err_Cd <>", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdGreaterThan(String value) {
            addCriterion("Ebank_Err_Cd >", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdGreaterThanOrEqualTo(String value) {
            addCriterion("Ebank_Err_Cd >=", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdLessThan(String value) {
            addCriterion("Ebank_Err_Cd <", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdLessThanOrEqualTo(String value) {
            addCriterion("Ebank_Err_Cd <=", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdLike(String value) {
            addCriterion("Ebank_Err_Cd like", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdNotLike(String value) {
            addCriterion("Ebank_Err_Cd not like", value, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdIn(List<String> values) {
            addCriterion("Ebank_Err_Cd in", values, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdNotIn(List<String> values) {
            addCriterion("Ebank_Err_Cd not in", values, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdBetween(String value1, String value2) {
            addCriterion("Ebank_Err_Cd between", value1, value2, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andEbankErrCdNotBetween(String value1, String value2) {
            addCriterion("Ebank_Err_Cd not between", value1, value2, "ebankErrCd");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoIsNull() {
            addCriterion("Tx_Err_Info is null");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoIsNotNull() {
            addCriterion("Tx_Err_Info is not null");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoEqualTo(String value) {
            addCriterion("Tx_Err_Info =", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoNotEqualTo(String value) {
            addCriterion("Tx_Err_Info <>", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoGreaterThan(String value) {
            addCriterion("Tx_Err_Info >", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoGreaterThanOrEqualTo(String value) {
            addCriterion("Tx_Err_Info >=", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoLessThan(String value) {
            addCriterion("Tx_Err_Info <", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoLessThanOrEqualTo(String value) {
            addCriterion("Tx_Err_Info <=", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoLike(String value) {
            addCriterion("Tx_Err_Info like", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoNotLike(String value) {
            addCriterion("Tx_Err_Info not like", value, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoIn(List<String> values) {
            addCriterion("Tx_Err_Info in", values, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoNotIn(List<String> values) {
            addCriterion("Tx_Err_Info not in", values, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoBetween(String value1, String value2) {
            addCriterion("Tx_Err_Info between", value1, value2, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andTxErrInfoNotBetween(String value1, String value2) {
            addCriterion("Tx_Err_Info not between", value1, value2, "txErrInfo");
            return (Criteria) this;
        }

        public Criteria andPartyIdIsNull() {
            addCriterion("Party_Id is null");
            return (Criteria) this;
        }

        public Criteria andPartyIdIsNotNull() {
            addCriterion("Party_Id is not null");
            return (Criteria) this;
        }

        public Criteria andPartyIdEqualTo(String value) {
            addCriterion("Party_Id =", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotEqualTo(String value) {
            addCriterion("Party_Id <>", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdGreaterThan(String value) {
            addCriterion("Party_Id >", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdGreaterThanOrEqualTo(String value) {
            addCriterion("Party_Id >=", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdLessThan(String value) {
            addCriterion("Party_Id <", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdLessThanOrEqualTo(String value) {
            addCriterion("Party_Id <=", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdLike(String value) {
            addCriterion("Party_Id like", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotLike(String value) {
            addCriterion("Party_Id not like", value, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdIn(List<String> values) {
            addCriterion("Party_Id in", values, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotIn(List<String> values) {
            addCriterion("Party_Id not in", values, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdBetween(String value1, String value2) {
            addCriterion("Party_Id between", value1, value2, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyIdNotBetween(String value1, String value2) {
            addCriterion("Party_Id not between", value1, value2, "partyId");
            return (Criteria) this;
        }

        public Criteria andPartyNameIsNull() {
            addCriterion("Party_Name is null");
            return (Criteria) this;
        }

        public Criteria andPartyNameIsNotNull() {
            addCriterion("Party_Name is not null");
            return (Criteria) this;
        }

        public Criteria andPartyNameEqualTo(String value) {
            addCriterion("Party_Name =", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameNotEqualTo(String value) {
            addCriterion("Party_Name <>", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameGreaterThan(String value) {
            addCriterion("Party_Name >", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameGreaterThanOrEqualTo(String value) {
            addCriterion("Party_Name >=", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameLessThan(String value) {
            addCriterion("Party_Name <", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameLessThanOrEqualTo(String value) {
            addCriterion("Party_Name <=", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameLike(String value) {
            addCriterion("Party_Name like", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameNotLike(String value) {
            addCriterion("Party_Name not like", value, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameIn(List<String> values) {
            addCriterion("Party_Name in", values, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameNotIn(List<String> values) {
            addCriterion("Party_Name not in", values, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameBetween(String value1, String value2) {
            addCriterion("Party_Name between", value1, value2, "partyName");
            return (Criteria) this;
        }

        public Criteria andPartyNameNotBetween(String value1, String value2) {
            addCriterion("Party_Name not between", value1, value2, "partyName");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdIsNull() {
            addCriterion("Med_Attestation_Mode_Cd is null");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdIsNotNull() {
            addCriterion("Med_Attestation_Mode_Cd is not null");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdEqualTo(String value) {
            addCriterion("Med_Attestation_Mode_Cd =", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdNotEqualTo(String value) {
            addCriterion("Med_Attestation_Mode_Cd <>", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdGreaterThan(String value) {
            addCriterion("Med_Attestation_Mode_Cd >", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdGreaterThanOrEqualTo(String value) {
            addCriterion("Med_Attestation_Mode_Cd >=", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdLessThan(String value) {
            addCriterion("Med_Attestation_Mode_Cd <", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdLessThanOrEqualTo(String value) {
            addCriterion("Med_Attestation_Mode_Cd <=", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdLike(String value) {
            addCriterion("Med_Attestation_Mode_Cd like", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdNotLike(String value) {
            addCriterion("Med_Attestation_Mode_Cd not like", value, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdIn(List<String> values) {
            addCriterion("Med_Attestation_Mode_Cd in", values, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdNotIn(List<String> values) {
            addCriterion("Med_Attestation_Mode_Cd not in", values, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdBetween(String value1, String value2) {
            addCriterion("Med_Attestation_Mode_Cd between", value1, value2, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andMedAttestationModeCdNotBetween(String value1, String value2) {
            addCriterion("Med_Attestation_Mode_Cd not between", value1, value2, "medAttestationModeCd");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdIsNull() {
            addCriterion("Logon_Card_Num_Id is null");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdIsNotNull() {
            addCriterion("Logon_Card_Num_Id is not null");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdEqualTo(String value) {
            addCriterion("Logon_Card_Num_Id =", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdNotEqualTo(String value) {
            addCriterion("Logon_Card_Num_Id <>", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdGreaterThan(String value) {
            addCriterion("Logon_Card_Num_Id >", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdGreaterThanOrEqualTo(String value) {
            addCriterion("Logon_Card_Num_Id >=", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdLessThan(String value) {
            addCriterion("Logon_Card_Num_Id <", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdLessThanOrEqualTo(String value) {
            addCriterion("Logon_Card_Num_Id <=", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdLike(String value) {
            addCriterion("Logon_Card_Num_Id like", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdNotLike(String value) {
            addCriterion("Logon_Card_Num_Id not like", value, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdIn(List<String> values) {
            addCriterion("Logon_Card_Num_Id in", values, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdNotIn(List<String> values) {
            addCriterion("Logon_Card_Num_Id not in", values, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdBetween(String value1, String value2) {
            addCriterion("Logon_Card_Num_Id between", value1, value2, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andLogonCardNumIdNotBetween(String value1, String value2) {
            addCriterion("Logon_Card_Num_Id not between", value1, value2, "logonCardNumId");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumIsNull() {
            addCriterion("Major_Cust_Num is null");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumIsNotNull() {
            addCriterion("Major_Cust_Num is not null");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumEqualTo(String value) {
            addCriterion("Major_Cust_Num =", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumNotEqualTo(String value) {
            addCriterion("Major_Cust_Num <>", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumGreaterThan(String value) {
            addCriterion("Major_Cust_Num >", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumGreaterThanOrEqualTo(String value) {
            addCriterion("Major_Cust_Num >=", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumLessThan(String value) {
            addCriterion("Major_Cust_Num <", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumLessThanOrEqualTo(String value) {
            addCriterion("Major_Cust_Num <=", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumLike(String value) {
            addCriterion("Major_Cust_Num like", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumNotLike(String value) {
            addCriterion("Major_Cust_Num not like", value, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumIn(List<String> values) {
            addCriterion("Major_Cust_Num in", values, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumNotIn(List<String> values) {
            addCriterion("Major_Cust_Num not in", values, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumBetween(String value1, String value2) {
            addCriterion("Major_Cust_Num between", value1, value2, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andMajorCustNumNotBetween(String value1, String value2) {
            addCriterion("Major_Cust_Num not between", value1, value2, "majorCustNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumIsNull() {
            addCriterion("Webbank_Rgst_Zone_Num is null");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumIsNotNull() {
            addCriterion("Webbank_Rgst_Zone_Num is not null");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumEqualTo(String value) {
            addCriterion("Webbank_Rgst_Zone_Num =", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumNotEqualTo(String value) {
            addCriterion("Webbank_Rgst_Zone_Num <>", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumGreaterThan(String value) {
            addCriterion("Webbank_Rgst_Zone_Num >", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumGreaterThanOrEqualTo(String value) {
            addCriterion("Webbank_Rgst_Zone_Num >=", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumLessThan(String value) {
            addCriterion("Webbank_Rgst_Zone_Num <", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumLessThanOrEqualTo(String value) {
            addCriterion("Webbank_Rgst_Zone_Num <=", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumLike(String value) {
            addCriterion("Webbank_Rgst_Zone_Num like", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumNotLike(String value) {
            addCriterion("Webbank_Rgst_Zone_Num not like", value, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumIn(List<String> values) {
            addCriterion("Webbank_Rgst_Zone_Num in", values, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumNotIn(List<String> values) {
            addCriterion("Webbank_Rgst_Zone_Num not in", values, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumBetween(String value1, String value2) {
            addCriterion("Webbank_Rgst_Zone_Num between", value1, value2, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstZoneNumNotBetween(String value1, String value2) {
            addCriterion("Webbank_Rgst_Zone_Num not between", value1, value2, "webbankRgstZoneNum");
            return (Criteria) this;
        }

        public Criteria andAppServIpIsNull() {
            addCriterion("App_Serv_Ip is null");
            return (Criteria) this;
        }

        public Criteria andAppServIpIsNotNull() {
            addCriterion("App_Serv_Ip is not null");
            return (Criteria) this;
        }

        public Criteria andAppServIpEqualTo(String value) {
            addCriterion("App_Serv_Ip =", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpNotEqualTo(String value) {
            addCriterion("App_Serv_Ip <>", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpGreaterThan(String value) {
            addCriterion("App_Serv_Ip >", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpGreaterThanOrEqualTo(String value) {
            addCriterion("App_Serv_Ip >=", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpLessThan(String value) {
            addCriterion("App_Serv_Ip <", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpLessThanOrEqualTo(String value) {
            addCriterion("App_Serv_Ip <=", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpLike(String value) {
            addCriterion("App_Serv_Ip like", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpNotLike(String value) {
            addCriterion("App_Serv_Ip not like", value, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpIn(List<String> values) {
            addCriterion("App_Serv_Ip in", values, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpNotIn(List<String> values) {
            addCriterion("App_Serv_Ip not in", values, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpBetween(String value1, String value2) {
            addCriterion("App_Serv_Ip between", value1, value2, "appServIp");
            return (Criteria) this;
        }

        public Criteria andAppServIpNotBetween(String value1, String value2) {
            addCriterion("App_Serv_Ip not between", value1, value2, "appServIp");
            return (Criteria) this;
        }

        public Criteria andCustIpIsNull() {
            addCriterion("Cust_Ip is null");
            return (Criteria) this;
        }

        public Criteria andCustIpIsNotNull() {
            addCriterion("Cust_Ip is not null");
            return (Criteria) this;
        }

        public Criteria andCustIpEqualTo(String value) {
            addCriterion("Cust_Ip =", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpNotEqualTo(String value) {
            addCriterion("Cust_Ip <>", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpGreaterThan(String value) {
            addCriterion("Cust_Ip >", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpGreaterThanOrEqualTo(String value) {
            addCriterion("Cust_Ip >=", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpLessThan(String value) {
            addCriterion("Cust_Ip <", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpLessThanOrEqualTo(String value) {
            addCriterion("Cust_Ip <=", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpLike(String value) {
            addCriterion("Cust_Ip like", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpNotLike(String value) {
            addCriterion("Cust_Ip not like", value, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpIn(List<String> values) {
            addCriterion("Cust_Ip in", values, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpNotIn(List<String> values) {
            addCriterion("Cust_Ip not in", values, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpBetween(String value1, String value2) {
            addCriterion("Cust_Ip between", value1, value2, "custIp");
            return (Criteria) this;
        }

        public Criteria andCustIpNotBetween(String value1, String value2) {
            addCriterion("Cust_Ip not between", value1, value2, "custIp");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumIsNull() {
            addCriterion("Webbank_Rgst_Org_Num is null");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumIsNotNull() {
            addCriterion("Webbank_Rgst_Org_Num is not null");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumEqualTo(String value) {
            addCriterion("Webbank_Rgst_Org_Num =", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumNotEqualTo(String value) {
            addCriterion("Webbank_Rgst_Org_Num <>", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumGreaterThan(String value) {
            addCriterion("Webbank_Rgst_Org_Num >", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumGreaterThanOrEqualTo(String value) {
            addCriterion("Webbank_Rgst_Org_Num >=", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumLessThan(String value) {
            addCriterion("Webbank_Rgst_Org_Num <", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumLessThanOrEqualTo(String value) {
            addCriterion("Webbank_Rgst_Org_Num <=", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumLike(String value) {
            addCriterion("Webbank_Rgst_Org_Num like", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumNotLike(String value) {
            addCriterion("Webbank_Rgst_Org_Num not like", value, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumIn(List<String> values) {
            addCriterion("Webbank_Rgst_Org_Num in", values, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumNotIn(List<String> values) {
            addCriterion("Webbank_Rgst_Org_Num not in", values, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumBetween(String value1, String value2) {
            addCriterion("Webbank_Rgst_Org_Num between", value1, value2, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andWebbankRgstOrgNumNotBetween(String value1, String value2) {
            addCriterion("Webbank_Rgst_Org_Num not between", value1, value2, "webbankRgstOrgNum");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("Memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("Memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("Memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("Memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("Memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("Memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("Memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("Memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("Memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("Memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("Memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("Memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("Memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("Memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andIpadIndIsNull() {
            addCriterion("Ipad_Ind is null");
            return (Criteria) this;
        }

        public Criteria andIpadIndIsNotNull() {
            addCriterion("Ipad_Ind is not null");
            return (Criteria) this;
        }

        public Criteria andIpadIndEqualTo(String value) {
            addCriterion("Ipad_Ind =", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndNotEqualTo(String value) {
            addCriterion("Ipad_Ind <>", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndGreaterThan(String value) {
            addCriterion("Ipad_Ind >", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndGreaterThanOrEqualTo(String value) {
            addCriterion("Ipad_Ind >=", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndLessThan(String value) {
            addCriterion("Ipad_Ind <", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndLessThanOrEqualTo(String value) {
            addCriterion("Ipad_Ind <=", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndLike(String value) {
            addCriterion("Ipad_Ind like", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndNotLike(String value) {
            addCriterion("Ipad_Ind not like", value, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndIn(List<String> values) {
            addCriterion("Ipad_Ind in", values, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndNotIn(List<String> values) {
            addCriterion("Ipad_Ind not in", values, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndBetween(String value1, String value2) {
            addCriterion("Ipad_Ind between", value1, value2, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andIpadIndNotBetween(String value1, String value2) {
            addCriterion("Ipad_Ind not between", value1, value2, "ipadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndIsNull() {
            addCriterion("Android_Sys_Pad_Ind is null");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndIsNotNull() {
            addCriterion("Android_Sys_Pad_Ind is not null");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndEqualTo(String value) {
            addCriterion("Android_Sys_Pad_Ind =", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndNotEqualTo(String value) {
            addCriterion("Android_Sys_Pad_Ind <>", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndGreaterThan(String value) {
            addCriterion("Android_Sys_Pad_Ind >", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndGreaterThanOrEqualTo(String value) {
            addCriterion("Android_Sys_Pad_Ind >=", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndLessThan(String value) {
            addCriterion("Android_Sys_Pad_Ind <", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndLessThanOrEqualTo(String value) {
            addCriterion("Android_Sys_Pad_Ind <=", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndLike(String value) {
            addCriterion("Android_Sys_Pad_Ind like", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndNotLike(String value) {
            addCriterion("Android_Sys_Pad_Ind not like", value, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndIn(List<String> values) {
            addCriterion("Android_Sys_Pad_Ind in", values, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndNotIn(List<String> values) {
            addCriterion("Android_Sys_Pad_Ind not in", values, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndBetween(String value1, String value2) {
            addCriterion("Android_Sys_Pad_Ind between", value1, value2, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andAndroidSysPadIndNotBetween(String value1, String value2) {
            addCriterion("Android_Sys_Pad_Ind not between", value1, value2, "androidSysPadInd");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNull() {
            addCriterion("Prod_Id is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("Prod_Id is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(String value) {
            addCriterion("Prod_Id =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(String value) {
            addCriterion("Prod_Id <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(String value) {
            addCriterion("Prod_Id >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(String value) {
            addCriterion("Prod_Id >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(String value) {
            addCriterion("Prod_Id <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(String value) {
            addCriterion("Prod_Id <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLike(String value) {
            addCriterion("Prod_Id like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotLike(String value) {
            addCriterion("Prod_Id not like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<String> values) {
            addCriterion("Prod_Id in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<String> values) {
            addCriterion("Prod_Id not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(String value1, String value2) {
            addCriterion("Prod_Id between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(String value1, String value2) {
            addCriterion("Prod_Id not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("Session_Id is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("Session_Id is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("Session_Id =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("Session_Id <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("Session_Id >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("Session_Id >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("Session_Id <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("Session_Id <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLike(String value) {
            addCriterion("Session_Id like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotLike(String value) {
            addCriterion("Session_Id not like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<String> values) {
            addCriterion("Session_Id in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<String> values) {
            addCriterion("Session_Id not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("Session_Id between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("Session_Id not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyIsNull() {
            addCriterion("Stat_Prod_Idtfy is null");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyIsNotNull() {
            addCriterion("Stat_Prod_Idtfy is not null");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyEqualTo(String value) {
            addCriterion("Stat_Prod_Idtfy =", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyNotEqualTo(String value) {
            addCriterion("Stat_Prod_Idtfy <>", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyGreaterThan(String value) {
            addCriterion("Stat_Prod_Idtfy >", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyGreaterThanOrEqualTo(String value) {
            addCriterion("Stat_Prod_Idtfy >=", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyLessThan(String value) {
            addCriterion("Stat_Prod_Idtfy <", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyLessThanOrEqualTo(String value) {
            addCriterion("Stat_Prod_Idtfy <=", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyLike(String value) {
            addCriterion("Stat_Prod_Idtfy like", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyNotLike(String value) {
            addCriterion("Stat_Prod_Idtfy not like", value, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyIn(List<String> values) {
            addCriterion("Stat_Prod_Idtfy in", values, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyNotIn(List<String> values) {
            addCriterion("Stat_Prod_Idtfy not in", values, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyBetween(String value1, String value2) {
            addCriterion("Stat_Prod_Idtfy between", value1, value2, "statProdIdtfy");
            return (Criteria) this;
        }

        public Criteria andStatProdIdtfyNotBetween(String value1, String value2) {
            addCriterion("Stat_Prod_Idtfy not between", value1, value2, "statProdIdtfy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logininfo
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}