package tiger.common.dal.persistence.icbc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RulesDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rules
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rules
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rules
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public RulesDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rules
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustNumIsNull() {
            addCriterion("Cust_Num is null");
            return (Criteria) this;
        }

        public Criteria andCustNumIsNotNull() {
            addCriterion("Cust_Num is not null");
            return (Criteria) this;
        }

        public Criteria andCustNumEqualTo(String value) {
            addCriterion("Cust_Num =", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumNotEqualTo(String value) {
            addCriterion("Cust_Num <>", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumGreaterThan(String value) {
            addCriterion("Cust_Num >", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumGreaterThanOrEqualTo(String value) {
            addCriterion("Cust_Num >=", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumLessThan(String value) {
            addCriterion("Cust_Num <", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumLessThanOrEqualTo(String value) {
            addCriterion("Cust_Num <=", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumLike(String value) {
            addCriterion("Cust_Num like", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumNotLike(String value) {
            addCriterion("Cust_Num not like", value, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumIn(List<String> values) {
            addCriterion("Cust_Num in", values, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumNotIn(List<String> values) {
            addCriterion("Cust_Num not in", values, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumBetween(String value1, String value2) {
            addCriterion("Cust_Num between", value1, value2, "custNum");
            return (Criteria) this;
        }

        public Criteria andCustNumNotBetween(String value1, String value2) {
            addCriterion("Cust_Num not between", value1, value2, "custNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumIsNull() {
            addCriterion("Tran_In_Card_Num is null");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumIsNotNull() {
            addCriterion("Tran_In_Card_Num is not null");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumEqualTo(String value) {
            addCriterion("Tran_In_Card_Num =", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumNotEqualTo(String value) {
            addCriterion("Tran_In_Card_Num <>", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumGreaterThan(String value) {
            addCriterion("Tran_In_Card_Num >", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumGreaterThanOrEqualTo(String value) {
            addCriterion("Tran_In_Card_Num >=", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumLessThan(String value) {
            addCriterion("Tran_In_Card_Num <", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumLessThanOrEqualTo(String value) {
            addCriterion("Tran_In_Card_Num <=", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumLike(String value) {
            addCriterion("Tran_In_Card_Num like", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumNotLike(String value) {
            addCriterion("Tran_In_Card_Num not like", value, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumIn(List<String> values) {
            addCriterion("Tran_In_Card_Num in", values, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumNotIn(List<String> values) {
            addCriterion("Tran_In_Card_Num not in", values, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumBetween(String value1, String value2) {
            addCriterion("Tran_In_Card_Num between", value1, value2, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTranInCardNumNotBetween(String value1, String value2) {
            addCriterion("Tran_In_Card_Num not between", value1, value2, "tranInCardNum");
            return (Criteria) this;
        }

        public Criteria andTxAmtIsNull() {
            addCriterion("Tx_Amt is null");
            return (Criteria) this;
        }

        public Criteria andTxAmtIsNotNull() {
            addCriterion("Tx_Amt is not null");
            return (Criteria) this;
        }

        public Criteria andTxAmtEqualTo(BigDecimal value) {
            addCriterion("Tx_Amt =", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtNotEqualTo(BigDecimal value) {
            addCriterion("Tx_Amt <>", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtGreaterThan(BigDecimal value) {
            addCriterion("Tx_Amt >", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Tx_Amt >=", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtLessThan(BigDecimal value) {
            addCriterion("Tx_Amt <", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Tx_Amt <=", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtIn(List<BigDecimal> values) {
            addCriterion("Tx_Amt in", values, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtNotIn(List<BigDecimal> values) {
            addCriterion("Tx_Amt not in", values, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Tx_Amt between", value1, value2, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Tx_Amt not between", value1, value2, "txAmt");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrIsNull() {
            addCriterion("Cust_Ip_Addr is null");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrIsNotNull() {
            addCriterion("Cust_Ip_Addr is not null");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrEqualTo(String value) {
            addCriterion("Cust_Ip_Addr =", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrNotEqualTo(String value) {
            addCriterion("Cust_Ip_Addr <>", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrGreaterThan(String value) {
            addCriterion("Cust_Ip_Addr >", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrGreaterThanOrEqualTo(String value) {
            addCriterion("Cust_Ip_Addr >=", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrLessThan(String value) {
            addCriterion("Cust_Ip_Addr <", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrLessThanOrEqualTo(String value) {
            addCriterion("Cust_Ip_Addr <=", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrLike(String value) {
            addCriterion("Cust_Ip_Addr like", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrNotLike(String value) {
            addCriterion("Cust_Ip_Addr not like", value, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrIn(List<String> values) {
            addCriterion("Cust_Ip_Addr in", values, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrNotIn(List<String> values) {
            addCriterion("Cust_Ip_Addr not in", values, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrBetween(String value1, String value2) {
            addCriterion("Cust_Ip_Addr between", value1, value2, "custIpAddr");
            return (Criteria) this;
        }

        public Criteria andCustIpAddrNotBetween(String value1, String value2) {
            addCriterion("Cust_Ip_Addr not between", value1, value2, "custIpAddr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rules
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rules
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}