package tiger.common.dal.persistence.icbc;

import java.util.ArrayList;
import java.util.List;

public class SelectedAndroidDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public SelectedAndroidDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andAndroididIsNull() {
            addCriterion("AndroidId is null");
            return (Criteria) this;
        }

        public Criteria andAndroididIsNotNull() {
            addCriterion("AndroidId is not null");
            return (Criteria) this;
        }

        public Criteria andAndroididEqualTo(String value) {
            addCriterion("AndroidId =", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididNotEqualTo(String value) {
            addCriterion("AndroidId <>", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididGreaterThan(String value) {
            addCriterion("AndroidId >", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididGreaterThanOrEqualTo(String value) {
            addCriterion("AndroidId >=", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididLessThan(String value) {
            addCriterion("AndroidId <", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididLessThanOrEqualTo(String value) {
            addCriterion("AndroidId <=", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididLike(String value) {
            addCriterion("AndroidId like", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididNotLike(String value) {
            addCriterion("AndroidId not like", value, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididIn(List<String> values) {
            addCriterion("AndroidId in", values, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididNotIn(List<String> values) {
            addCriterion("AndroidId not in", values, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididBetween(String value1, String value2) {
            addCriterion("AndroidId between", value1, value2, "androidid");
            return (Criteria) this;
        }

        public Criteria andAndroididNotBetween(String value1, String value2) {
            addCriterion("AndroidId not between", value1, value2, "androidid");
            return (Criteria) this;
        }

        public Criteria andSerialnumberIsNull() {
            addCriterion("serialNumber is null");
            return (Criteria) this;
        }

        public Criteria andSerialnumberIsNotNull() {
            addCriterion("serialNumber is not null");
            return (Criteria) this;
        }

        public Criteria andSerialnumberEqualTo(String value) {
            addCriterion("serialNumber =", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberNotEqualTo(String value) {
            addCriterion("serialNumber <>", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberGreaterThan(String value) {
            addCriterion("serialNumber >", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberGreaterThanOrEqualTo(String value) {
            addCriterion("serialNumber >=", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberLessThan(String value) {
            addCriterion("serialNumber <", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberLessThanOrEqualTo(String value) {
            addCriterion("serialNumber <=", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberLike(String value) {
            addCriterion("serialNumber like", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberNotLike(String value) {
            addCriterion("serialNumber not like", value, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberIn(List<String> values) {
            addCriterion("serialNumber in", values, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberNotIn(List<String> values) {
            addCriterion("serialNumber not in", values, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberBetween(String value1, String value2) {
            addCriterion("serialNumber between", value1, value2, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andSerialnumberNotBetween(String value1, String value2) {
            addCriterion("serialNumber not between", value1, value2, "serialnumber");
            return (Criteria) this;
        }

        public Criteria andMacIsNull() {
            addCriterion("MAC is null");
            return (Criteria) this;
        }

        public Criteria andMacIsNotNull() {
            addCriterion("MAC is not null");
            return (Criteria) this;
        }

        public Criteria andMacEqualTo(String value) {
            addCriterion("MAC =", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotEqualTo(String value) {
            addCriterion("MAC <>", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThan(String value) {
            addCriterion("MAC >", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThanOrEqualTo(String value) {
            addCriterion("MAC >=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThan(String value) {
            addCriterion("MAC <", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThanOrEqualTo(String value) {
            addCriterion("MAC <=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLike(String value) {
            addCriterion("MAC like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotLike(String value) {
            addCriterion("MAC not like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacIn(List<String> values) {
            addCriterion("MAC in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotIn(List<String> values) {
            addCriterion("MAC not in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacBetween(String value1, String value2) {
            addCriterion("MAC between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotBetween(String value1, String value2) {
            addCriterion("MAC not between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andTimeareaIsNull() {
            addCriterion("timeArea is null");
            return (Criteria) this;
        }

        public Criteria andTimeareaIsNotNull() {
            addCriterion("timeArea is not null");
            return (Criteria) this;
        }

        public Criteria andTimeareaEqualTo(String value) {
            addCriterion("timeArea =", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaNotEqualTo(String value) {
            addCriterion("timeArea <>", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaGreaterThan(String value) {
            addCriterion("timeArea >", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaGreaterThanOrEqualTo(String value) {
            addCriterion("timeArea >=", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaLessThan(String value) {
            addCriterion("timeArea <", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaLessThanOrEqualTo(String value) {
            addCriterion("timeArea <=", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaLike(String value) {
            addCriterion("timeArea like", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaNotLike(String value) {
            addCriterion("timeArea not like", value, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaIn(List<String> values) {
            addCriterion("timeArea in", values, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaNotIn(List<String> values) {
            addCriterion("timeArea not in", values, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaBetween(String value1, String value2) {
            addCriterion("timeArea between", value1, value2, "timearea");
            return (Criteria) this;
        }

        public Criteria andTimeareaNotBetween(String value1, String value2) {
            addCriterion("timeArea not between", value1, value2, "timearea");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeIsNull() {
            addCriterion("autoLockTime is null");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeIsNotNull() {
            addCriterion("autoLockTime is not null");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeEqualTo(String value) {
            addCriterion("autoLockTime =", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeNotEqualTo(String value) {
            addCriterion("autoLockTime <>", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeGreaterThan(String value) {
            addCriterion("autoLockTime >", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeGreaterThanOrEqualTo(String value) {
            addCriterion("autoLockTime >=", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeLessThan(String value) {
            addCriterion("autoLockTime <", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeLessThanOrEqualTo(String value) {
            addCriterion("autoLockTime <=", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeLike(String value) {
            addCriterion("autoLockTime like", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeNotLike(String value) {
            addCriterion("autoLockTime not like", value, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeIn(List<String> values) {
            addCriterion("autoLockTime in", values, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeNotIn(List<String> values) {
            addCriterion("autoLockTime not in", values, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeBetween(String value1, String value2) {
            addCriterion("autoLockTime between", value1, value2, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andAutolocktimeNotBetween(String value1, String value2) {
            addCriterion("autoLockTime not between", value1, value2, "autolocktime");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodIsNull() {
            addCriterion("getLocationMethod is null");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodIsNotNull() {
            addCriterion("getLocationMethod is not null");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodEqualTo(String value) {
            addCriterion("getLocationMethod =", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodNotEqualTo(String value) {
            addCriterion("getLocationMethod <>", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodGreaterThan(String value) {
            addCriterion("getLocationMethod >", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodGreaterThanOrEqualTo(String value) {
            addCriterion("getLocationMethod >=", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodLessThan(String value) {
            addCriterion("getLocationMethod <", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodLessThanOrEqualTo(String value) {
            addCriterion("getLocationMethod <=", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodLike(String value) {
            addCriterion("getLocationMethod like", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodNotLike(String value) {
            addCriterion("getLocationMethod not like", value, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodIn(List<String> values) {
            addCriterion("getLocationMethod in", values, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodNotIn(List<String> values) {
            addCriterion("getLocationMethod not in", values, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodBetween(String value1, String value2) {
            addCriterion("getLocationMethod between", value1, value2, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andGetlocationmethodNotBetween(String value1, String value2) {
            addCriterion("getLocationMethod not between", value1, value2, "getlocationmethod");
            return (Criteria) this;
        }

        public Criteria andInputinfoIsNull() {
            addCriterion("inputInfo is null");
            return (Criteria) this;
        }

        public Criteria andInputinfoIsNotNull() {
            addCriterion("inputInfo is not null");
            return (Criteria) this;
        }

        public Criteria andInputinfoEqualTo(String value) {
            addCriterion("inputInfo =", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoNotEqualTo(String value) {
            addCriterion("inputInfo <>", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoGreaterThan(String value) {
            addCriterion("inputInfo >", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoGreaterThanOrEqualTo(String value) {
            addCriterion("inputInfo >=", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoLessThan(String value) {
            addCriterion("inputInfo <", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoLessThanOrEqualTo(String value) {
            addCriterion("inputInfo <=", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoLike(String value) {
            addCriterion("inputInfo like", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoNotLike(String value) {
            addCriterion("inputInfo not like", value, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoIn(List<String> values) {
            addCriterion("inputInfo in", values, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoNotIn(List<String> values) {
            addCriterion("inputInfo not in", values, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoBetween(String value1, String value2) {
            addCriterion("inputInfo between", value1, value2, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andInputinfoNotBetween(String value1, String value2) {
            addCriterion("inputInfo not between", value1, value2, "inputinfo");
            return (Criteria) this;
        }

        public Criteria andFontlistIsNull() {
            addCriterion("fontList is null");
            return (Criteria) this;
        }

        public Criteria andFontlistIsNotNull() {
            addCriterion("fontList is not null");
            return (Criteria) this;
        }

        public Criteria andFontlistEqualTo(String value) {
            addCriterion("fontList =", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistNotEqualTo(String value) {
            addCriterion("fontList <>", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistGreaterThan(String value) {
            addCriterion("fontList >", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistGreaterThanOrEqualTo(String value) {
            addCriterion("fontList >=", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistLessThan(String value) {
            addCriterion("fontList <", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistLessThanOrEqualTo(String value) {
            addCriterion("fontList <=", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistLike(String value) {
            addCriterion("fontList like", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistNotLike(String value) {
            addCriterion("fontList not like", value, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistIn(List<String> values) {
            addCriterion("fontList in", values, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistNotIn(List<String> values) {
            addCriterion("fontList not in", values, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistBetween(String value1, String value2) {
            addCriterion("fontList between", value1, value2, "fontlist");
            return (Criteria) this;
        }

        public Criteria andFontlistNotBetween(String value1, String value2) {
            addCriterion("fontList not between", value1, value2, "fontlist");
            return (Criteria) this;
        }

        public Criteria andPhonebellIsNull() {
            addCriterion("phoneBell is null");
            return (Criteria) this;
        }

        public Criteria andPhonebellIsNotNull() {
            addCriterion("phoneBell is not null");
            return (Criteria) this;
        }

        public Criteria andPhonebellEqualTo(String value) {
            addCriterion("phoneBell =", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellNotEqualTo(String value) {
            addCriterion("phoneBell <>", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellGreaterThan(String value) {
            addCriterion("phoneBell >", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellGreaterThanOrEqualTo(String value) {
            addCriterion("phoneBell >=", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellLessThan(String value) {
            addCriterion("phoneBell <", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellLessThanOrEqualTo(String value) {
            addCriterion("phoneBell <=", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellLike(String value) {
            addCriterion("phoneBell like", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellNotLike(String value) {
            addCriterion("phoneBell not like", value, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellIn(List<String> values) {
            addCriterion("phoneBell in", values, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellNotIn(List<String> values) {
            addCriterion("phoneBell not in", values, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellBetween(String value1, String value2) {
            addCriterion("phoneBell between", value1, value2, "phonebell");
            return (Criteria) this;
        }

        public Criteria andPhonebellNotBetween(String value1, String value2) {
            addCriterion("phoneBell not between", value1, value2, "phonebell");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleIsNull() {
            addCriterion("lastPosVisible is null");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleIsNotNull() {
            addCriterion("lastPosVisible is not null");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleEqualTo(String value) {
            addCriterion("lastPosVisible =", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleNotEqualTo(String value) {
            addCriterion("lastPosVisible <>", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleGreaterThan(String value) {
            addCriterion("lastPosVisible >", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleGreaterThanOrEqualTo(String value) {
            addCriterion("lastPosVisible >=", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleLessThan(String value) {
            addCriterion("lastPosVisible <", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleLessThanOrEqualTo(String value) {
            addCriterion("lastPosVisible <=", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleLike(String value) {
            addCriterion("lastPosVisible like", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleNotLike(String value) {
            addCriterion("lastPosVisible not like", value, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleIn(List<String> values) {
            addCriterion("lastPosVisible in", values, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleNotIn(List<String> values) {
            addCriterion("lastPosVisible not in", values, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleBetween(String value1, String value2) {
            addCriterion("lastPosVisible between", value1, value2, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andLastposvisibleNotBetween(String value1, String value2) {
            addCriterion("lastPosVisible not between", value1, value2, "lastposvisible");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("IP in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("IP not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andBelllistIsNull() {
            addCriterion("bellList is null");
            return (Criteria) this;
        }

        public Criteria andBelllistIsNotNull() {
            addCriterion("bellList is not null");
            return (Criteria) this;
        }

        public Criteria andBelllistEqualTo(String value) {
            addCriterion("bellList =", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistNotEqualTo(String value) {
            addCriterion("bellList <>", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistGreaterThan(String value) {
            addCriterion("bellList >", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistGreaterThanOrEqualTo(String value) {
            addCriterion("bellList >=", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistLessThan(String value) {
            addCriterion("bellList <", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistLessThanOrEqualTo(String value) {
            addCriterion("bellList <=", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistLike(String value) {
            addCriterion("bellList like", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistNotLike(String value) {
            addCriterion("bellList not like", value, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistIn(List<String> values) {
            addCriterion("bellList in", values, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistNotIn(List<String> values) {
            addCriterion("bellList not in", values, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistBetween(String value1, String value2) {
            addCriterion("bellList between", value1, value2, "belllist");
            return (Criteria) this;
        }

        public Criteria andBelllistNotBetween(String value1, String value2) {
            addCriterion("bellList not between", value1, value2, "belllist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistIsNull() {
            addCriterion("systemAppList is null");
            return (Criteria) this;
        }

        public Criteria andSystemapplistIsNotNull() {
            addCriterion("systemAppList is not null");
            return (Criteria) this;
        }

        public Criteria andSystemapplistEqualTo(String value) {
            addCriterion("systemAppList =", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistNotEqualTo(String value) {
            addCriterion("systemAppList <>", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistGreaterThan(String value) {
            addCriterion("systemAppList >", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistGreaterThanOrEqualTo(String value) {
            addCriterion("systemAppList >=", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistLessThan(String value) {
            addCriterion("systemAppList <", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistLessThanOrEqualTo(String value) {
            addCriterion("systemAppList <=", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistLike(String value) {
            addCriterion("systemAppList like", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistNotLike(String value) {
            addCriterion("systemAppList not like", value, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistIn(List<String> values) {
            addCriterion("systemAppList in", values, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistNotIn(List<String> values) {
            addCriterion("systemAppList not in", values, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistBetween(String value1, String value2) {
            addCriterion("systemAppList between", value1, value2, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andSystemapplistNotBetween(String value1, String value2) {
            addCriterion("systemAppList not between", value1, value2, "systemapplist");
            return (Criteria) this;
        }

        public Criteria andScreeninfoIsNull() {
            addCriterion("screenInfo is null");
            return (Criteria) this;
        }

        public Criteria andScreeninfoIsNotNull() {
            addCriterion("screenInfo is not null");
            return (Criteria) this;
        }

        public Criteria andScreeninfoEqualTo(String value) {
            addCriterion("screenInfo =", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoNotEqualTo(String value) {
            addCriterion("screenInfo <>", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoGreaterThan(String value) {
            addCriterion("screenInfo >", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoGreaterThanOrEqualTo(String value) {
            addCriterion("screenInfo >=", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoLessThan(String value) {
            addCriterion("screenInfo <", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoLessThanOrEqualTo(String value) {
            addCriterion("screenInfo <=", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoLike(String value) {
            addCriterion("screenInfo like", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoNotLike(String value) {
            addCriterion("screenInfo not like", value, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoIn(List<String> values) {
            addCriterion("screenInfo in", values, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoNotIn(List<String> values) {
            addCriterion("screenInfo not in", values, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoBetween(String value1, String value2) {
            addCriterion("screenInfo between", value1, value2, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andScreeninfoNotBetween(String value1, String value2) {
            addCriterion("screenInfo not between", value1, value2, "screeninfo");
            return (Criteria) this;
        }

        public Criteria andInnerspaceIsNull() {
            addCriterion("innerSpace is null");
            return (Criteria) this;
        }

        public Criteria andInnerspaceIsNotNull() {
            addCriterion("innerSpace is not null");
            return (Criteria) this;
        }

        public Criteria andInnerspaceEqualTo(String value) {
            addCriterion("innerSpace =", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceNotEqualTo(String value) {
            addCriterion("innerSpace <>", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceGreaterThan(String value) {
            addCriterion("innerSpace >", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceGreaterThanOrEqualTo(String value) {
            addCriterion("innerSpace >=", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceLessThan(String value) {
            addCriterion("innerSpace <", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceLessThanOrEqualTo(String value) {
            addCriterion("innerSpace <=", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceLike(String value) {
            addCriterion("innerSpace like", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceNotLike(String value) {
            addCriterion("innerSpace not like", value, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceIn(List<String> values) {
            addCriterion("innerSpace in", values, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceNotIn(List<String> values) {
            addCriterion("innerSpace not in", values, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceBetween(String value1, String value2) {
            addCriterion("innerSpace between", value1, value2, "innerspace");
            return (Criteria) this;
        }

        public Criteria andInnerspaceNotBetween(String value1, String value2) {
            addCriterion("innerSpace not between", value1, value2, "innerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceIsNull() {
            addCriterion("outerSpace is null");
            return (Criteria) this;
        }

        public Criteria andOuterspaceIsNotNull() {
            addCriterion("outerSpace is not null");
            return (Criteria) this;
        }

        public Criteria andOuterspaceEqualTo(String value) {
            addCriterion("outerSpace =", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceNotEqualTo(String value) {
            addCriterion("outerSpace <>", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceGreaterThan(String value) {
            addCriterion("outerSpace >", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceGreaterThanOrEqualTo(String value) {
            addCriterion("outerSpace >=", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceLessThan(String value) {
            addCriterion("outerSpace <", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceLessThanOrEqualTo(String value) {
            addCriterion("outerSpace <=", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceLike(String value) {
            addCriterion("outerSpace like", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceNotLike(String value) {
            addCriterion("outerSpace not like", value, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceIn(List<String> values) {
            addCriterion("outerSpace in", values, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceNotIn(List<String> values) {
            addCriterion("outerSpace not in", values, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceBetween(String value1, String value2) {
            addCriterion("outerSpace between", value1, value2, "outerspace");
            return (Criteria) this;
        }

        public Criteria andOuterspaceNotBetween(String value1, String value2) {
            addCriterion("outerSpace not between", value1, value2, "outerspace");
            return (Criteria) this;
        }

        public Criteria andUseragentIsNull() {
            addCriterion("userAgent is null");
            return (Criteria) this;
        }

        public Criteria andUseragentIsNotNull() {
            addCriterion("userAgent is not null");
            return (Criteria) this;
        }

        public Criteria andUseragentEqualTo(String value) {
            addCriterion("userAgent =", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotEqualTo(String value) {
            addCriterion("userAgent <>", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentGreaterThan(String value) {
            addCriterion("userAgent >", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentGreaterThanOrEqualTo(String value) {
            addCriterion("userAgent >=", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentLessThan(String value) {
            addCriterion("userAgent <", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentLessThanOrEqualTo(String value) {
            addCriterion("userAgent <=", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentLike(String value) {
            addCriterion("userAgent like", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotLike(String value) {
            addCriterion("userAgent not like", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentIn(List<String> values) {
            addCriterion("userAgent in", values, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotIn(List<String> values) {
            addCriterion("userAgent not in", values, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentBetween(String value1, String value2) {
            addCriterion("userAgent between", value1, value2, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotBetween(String value1, String value2) {
            addCriterion("userAgent not between", value1, value2, "useragent");
            return (Criteria) this;
        }

        public Criteria andLabelIsNull() {
            addCriterion("label is null");
            return (Criteria) this;
        }

        public Criteria andLabelIsNotNull() {
            addCriterion("label is not null");
            return (Criteria) this;
        }

        public Criteria andLabelEqualTo(Integer value) {
            addCriterion("label =", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotEqualTo(Integer value) {
            addCriterion("label <>", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThan(Integer value) {
            addCriterion("label >", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelGreaterThanOrEqualTo(Integer value) {
            addCriterion("label >=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThan(Integer value) {
            addCriterion("label <", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelLessThanOrEqualTo(Integer value) {
            addCriterion("label <=", value, "label");
            return (Criteria) this;
        }

        public Criteria andLabelIn(List<Integer> values) {
            addCriterion("label in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotIn(List<Integer> values) {
            addCriterion("label not in", values, "label");
            return (Criteria) this;
        }

        public Criteria andLabelBetween(Integer value1, Integer value2) {
            addCriterion("label between", value1, value2, "label");
            return (Criteria) this;
        }

        public Criteria andLabelNotBetween(Integer value1, Integer value2) {
            addCriterion("label not between", value1, value2, "label");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table selected_android
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table selected_android
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}